import {DINOSAUR_EGG_CREATION_STEPS, DINOSAUR_INCUBATION_STEPS, DINOSAUR_TYPE_ID} from "./fieldNames";

export default {
    [DINOSAUR_INCUBATION_STEPS]: [''],
    [DINOSAUR_EGG_CREATION_STEPS]: [''],
    [DINOSAUR_TYPE_ID]: ''
}