import {
    AVIARIES_SELECTOR, DECORATIONS_SELECTOR,
    DINOSAURS_SELECTOR, DOCUMENT_NAME,
    THEME_ZONE_PROJECT_MANAGER,
    THEME_ZONE_PROJECT_NAME
} from "./fieldNames";

export default {
    [THEME_ZONE_PROJECT_NAME]: '',
    [THEME_ZONE_PROJECT_MANAGER]: '',
    [DINOSAURS_SELECTOR]: [],
    [AVIARIES_SELECTOR]: [],
    [DECORATIONS_SELECTOR]: [],
    [DOCUMENT_NAME]: ''
}