/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AssigneeDTO
 */
export interface AssigneeDTO {
    /**
     *
     * @type {number}
     * @memberof AssigneeDTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof AssigneeDTO
     */
    username?: string;
}
export declare function AssigneeDTOFromJSON(json: any): AssigneeDTO;
export declare function AssigneeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssigneeDTO;
export declare function AssigneeDTOToJSON(value?: AssigneeDTO | null): any;
