/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AssigneeDTO
 */
export interface AssigneeDTO {
    /**
     *
     * @type {number}
     * @memberof AssigneeDTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof AssigneeDTO
     */
    username?: string;
}
export declare function AssigneeDTOFromJSON(json: any): AssigneeDTO;
export declare function AssigneeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssigneeDTO;
export declare function AssigneeDTOToJSON(value?: AssigneeDTO | null): any;
