"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var DocumentOutputTO_1 = require("./DocumentOutputTO");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function AviaryPassportOutputTOFromJSON(json) {
    return AviaryPassportOutputTOFromJSONTyped(json, false);
}
exports.AviaryPassportOutputTOFromJSON = AviaryPassportOutputTOFromJSON;
function AviaryPassportOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return __assign({}, DocumentOutputTO_1.DocumentOutputTOFromJSONTyped(json, ignoreDiscriminator), { 'aviaryType': !runtime_1.exists(json, 'aviaryType') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['aviaryType']), 'code': !runtime_1.exists(json, 'code') ? undefined : json['code'], 'builtDate': !runtime_1.exists(json, 'builtDate') ? undefined : json['builtDate'], 'revisionPeriod': !runtime_1.exists(json, 'revisionPeriod') ? undefined : json['revisionPeriod'], 'status': !runtime_1.exists(json, 'status') ? undefined : json['status'] });
}
exports.AviaryPassportOutputTOFromJSONTyped = AviaryPassportOutputTOFromJSONTyped;
function AviaryPassportOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return __assign({}, DocumentOutputTO_1.DocumentOutputTOToJSON(value), { 'aviaryType': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.aviaryType), 'code': value.code, 'builtDate': value.builtDate, 'revisionPeriod': value.revisionPeriod, 'status': value.status });
}
exports.AviaryPassportOutputTOToJSON = AviaryPassportOutputTOToJSON;
