/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AviaryTaskDTOAllOf
 */
export interface AviaryTaskDTOAllOf {
    /**
     *
     * @type {number}
     * @memberof AviaryTaskDTOAllOf
     */
    aviaryTypeId?: number;
    /**
     *
     * @type {number}
     * @memberof AviaryTaskDTOAllOf
     */
    square?: number;
}
export declare function AviaryTaskDTOAllOfFromJSON(json: any): AviaryTaskDTOAllOf;
export declare function AviaryTaskDTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AviaryTaskDTOAllOf;
export declare function AviaryTaskDTOAllOfToJSON(value?: AviaryTaskDTOAllOf | null): any;
