/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AviaryPassportInputTOAllOf
 */
export interface AviaryPassportInputTOAllOf {
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTOAllOf
     */
    aviaryTypeId: number;
    /**
     *
     * @type {string}
     * @memberof AviaryPassportInputTOAllOf
     */
    code: string;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTOAllOf
     */
    square: number;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTOAllOf
     */
    builtDate: number;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTOAllOf
     */
    revisionPeriod: number;
    /**
     *
     * @type {string}
     * @memberof AviaryPassportInputTOAllOf
     */
    status?: string;
}
export declare function AviaryPassportInputTOAllOfFromJSON(json: any): AviaryPassportInputTOAllOf;
export declare function AviaryPassportInputTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AviaryPassportInputTOAllOf;
export declare function AviaryPassportInputTOAllOfToJSON(value?: AviaryPassportInputTOAllOf | null): any;
