/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskTO } from './TaskTO';
/**
 *
 * @export
 * @interface AviaryTaskDTO
 */
export interface AviaryTaskDTO extends TaskTO {
    /**
     *
     * @type {number}
     * @memberof AviaryTaskDTO
     */
    aviaryTypeId?: number;
    /**
     *
     * @type {number}
     * @memberof AviaryTaskDTO
     */
    square?: number;
}
export declare function AviaryTaskDTOFromJSON(json: any): AviaryTaskDTO;
export declare function AviaryTaskDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AviaryTaskDTO;
export declare function AviaryTaskDTOToJSON(value?: AviaryTaskDTO | null): any;
