/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentInputTO } from './DocumentInputTO';
/**
 *
 * @export
 * @interface AviaryPassportInputTO
 */
export interface AviaryPassportInputTO extends DocumentInputTO {
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTO
     */
    aviaryTypeId: number;
    /**
     *
     * @type {string}
     * @memberof AviaryPassportInputTO
     */
    code: string;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTO
     */
    square: number;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTO
     */
    builtDate: number;
    /**
     *
     * @type {number}
     * @memberof AviaryPassportInputTO
     */
    revisionPeriod: number;
    /**
     *
     * @type {string}
     * @memberof AviaryPassportInputTO
     */
    status?: string;
}
export declare function AviaryPassportInputTOFromJSON(json: any): AviaryPassportInputTO;
export declare function AviaryPassportInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AviaryPassportInputTO;
export declare function AviaryPassportInputTOToJSON(value?: AviaryPassportInputTO | null): any;
