"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function AviaryTaskDTOAllOfFromJSON(json) {
    return AviaryTaskDTOAllOfFromJSONTyped(json, false);
}
exports.AviaryTaskDTOAllOfFromJSON = AviaryTaskDTOAllOfFromJSON;
function AviaryTaskDTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'aviaryTypeId': !runtime_1.exists(json, 'aviaryTypeId') ? undefined : json['aviaryTypeId'],
        'square': !runtime_1.exists(json, 'square') ? undefined : json['square'],
    };
}
exports.AviaryTaskDTOAllOfFromJSONTyped = AviaryTaskDTOAllOfFromJSONTyped;
function AviaryTaskDTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'aviaryTypeId': value.aviaryTypeId,
        'square': value.square,
    };
}
exports.AviaryTaskDTOAllOfToJSON = AviaryTaskDTOAllOfToJSON;
