"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function AviaryPassportInputTOAllOfFromJSON(json) {
    return AviaryPassportInputTOAllOfFromJSONTyped(json, false);
}
exports.AviaryPassportInputTOAllOfFromJSON = AviaryPassportInputTOAllOfFromJSON;
function AviaryPassportInputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'aviaryTypeId': json['aviaryTypeId'],
        'code': json['code'],
        'square': json['square'],
        'builtDate': json['builtDate'],
        'revisionPeriod': json['revisionPeriod'],
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
    };
}
exports.AviaryPassportInputTOAllOfFromJSONTyped = AviaryPassportInputTOAllOfFromJSONTyped;
function AviaryPassportInputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'aviaryTypeId': value.aviaryTypeId,
        'code': value.code,
        'square': value.square,
        'builtDate': value.builtDate,
        'revisionPeriod': value.revisionPeriod,
        'status': value.status,
    };
}
exports.AviaryPassportInputTOAllOfToJSON = AviaryPassportInputTOAllOfToJSON;
