"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function AviaryPassportOutputTOAllOfFromJSON(json) {
    return AviaryPassportOutputTOAllOfFromJSONTyped(json, false);
}
exports.AviaryPassportOutputTOAllOfFromJSON = AviaryPassportOutputTOAllOfFromJSON;
function AviaryPassportOutputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'aviaryType': !runtime_1.exists(json, 'aviaryType') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['aviaryType']),
        'code': !runtime_1.exists(json, 'code') ? undefined : json['code'],
        'builtDate': !runtime_1.exists(json, 'builtDate') ? undefined : json['builtDate'],
        'revisionPeriod': !runtime_1.exists(json, 'revisionPeriod') ? undefined : json['revisionPeriod'],
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
    };
}
exports.AviaryPassportOutputTOAllOfFromJSONTyped = AviaryPassportOutputTOAllOfFromJSONTyped;
function AviaryPassportOutputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'aviaryType': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.aviaryType),
        'code': value.code,
        'builtDate': value.builtDate,
        'revisionPeriod': value.revisionPeriod,
        'status': value.status,
    };
}
exports.AviaryPassportOutputTOAllOfToJSON = AviaryPassportOutputTOAllOfToJSON;
