"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var TaskTO_1 = require("./TaskTO");
function AviaryTaskDTOFromJSON(json) {
    return AviaryTaskDTOFromJSONTyped(json, false);
}
exports.AviaryTaskDTOFromJSON = AviaryTaskDTOFromJSON;
function AviaryTaskDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return __assign({}, TaskTO_1.TaskTOFromJSONTyped(json, ignoreDiscriminator), { 'aviaryTypeId': !runtime_1.exists(json, 'aviaryTypeId') ? undefined : json['aviaryTypeId'], 'square': !runtime_1.exists(json, 'square') ? undefined : json['square'] });
}
exports.AviaryTaskDTOFromJSONTyped = AviaryTaskDTOFromJSONTyped;
function AviaryTaskDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return __assign({}, TaskTO_1.TaskTOToJSON(value), { 'aviaryTypeId': value.aviaryTypeId, 'square': value.square });
}
exports.AviaryTaskDTOToJSON = AviaryTaskDTOToJSON;
