/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateUserTO
 */
export interface CreateUserTO {
    /**
     *
     * @type {string}
     * @memberof CreateUserTO
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserTO
     */
    password?: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserTO
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserTO
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserTO
     */
    department: CreateUserTODepartmentEnum;
    /**
     *
     * @type {Set<number>}
     * @memberof CreateUserTO
     */
    groupIds?: Set<number>;
}
/**
* @export
* @enum {string}
*/
export declare enum CreateUserTODepartmentEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    Security = "SECURITY",
    Administration = "ADMINISTRATION",
    Maintenance = "MAINTENANCE",
    Accommodation = "ACCOMMODATION"
}
export declare function CreateUserTOFromJSON(json: any): CreateUserTO;
export declare function CreateUserTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserTO;
export declare function CreateUserTOToJSON(value?: CreateUserTO | null): any;
