/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentOutputTO } from './DocumentOutputTO';
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface DinosaurPassportOutputTO
 */
export interface DinosaurPassportOutputTO extends DocumentOutputTO {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof DinosaurPassportOutputTO
     */
    dinosaurType?: SimpleEntityOutputTO;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportOutputTO
     */
    dinosaurName?: string;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportOutputTO
     */
    weight?: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportOutputTO
     */
    height?: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportOutputTO
     */
    incubated?: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportOutputTO
     */
    revisionPeriod?: number;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportOutputTO
     */
    status?: string;
}
export declare function DinosaurPassportOutputTOFromJSON(json: any): DinosaurPassportOutputTO;
export declare function DinosaurPassportOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DinosaurPassportOutputTO;
export declare function DinosaurPassportOutputTOToJSON(value?: DinosaurPassportOutputTO | null): any;
