/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentInputTO } from './DocumentInputTO';
/**
 *
 * @export
 * @interface DinosaurPassportInputTO
 */
export interface DinosaurPassportInputTO extends DocumentInputTO {
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTO
     */
    dinosaurTypeId: number;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportInputTO
     */
    dinosaurName?: string;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTO
     */
    weight: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTO
     */
    height: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTO
     */
    incubated: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTO
     */
    revisionPeriod: number;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportInputTO
     */
    status?: string;
}
export declare function DinosaurPassportInputTOFromJSON(json: any): DinosaurPassportInputTO;
export declare function DinosaurPassportInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DinosaurPassportInputTO;
export declare function DinosaurPassportInputTOToJSON(value?: DinosaurPassportInputTO | null): any;
