/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DinosaurPassportInputTOAllOf
 */
export interface DinosaurPassportInputTOAllOf {
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTOAllOf
     */
    dinosaurTypeId: number;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportInputTOAllOf
     */
    dinosaurName?: string;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTOAllOf
     */
    weight: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTOAllOf
     */
    height: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTOAllOf
     */
    incubated: number;
    /**
     *
     * @type {number}
     * @memberof DinosaurPassportInputTOAllOf
     */
    revisionPeriod: number;
    /**
     *
     * @type {string}
     * @memberof DinosaurPassportInputTOAllOf
     */
    status?: string;
}
export declare function DinosaurPassportInputTOAllOfFromJSON(json: any): DinosaurPassportInputTOAllOf;
export declare function DinosaurPassportInputTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DinosaurPassportInputTOAllOf;
export declare function DinosaurPassportInputTOAllOfToJSON(value?: DinosaurPassportInputTOAllOf | null): any;
