"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function DinosaurPassportInputTOAllOfFromJSON(json) {
    return DinosaurPassportInputTOAllOfFromJSONTyped(json, false);
}
exports.DinosaurPassportInputTOAllOfFromJSON = DinosaurPassportInputTOAllOfFromJSON;
function DinosaurPassportInputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'dinosaurTypeId': json['dinosaurTypeId'],
        'dinosaurName': !runtime_1.exists(json, 'dinosaurName') ? undefined : json['dinosaurName'],
        'weight': json['weight'],
        'height': json['height'],
        'incubated': json['incubated'],
        'revisionPeriod': json['revisionPeriod'],
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
    };
}
exports.DinosaurPassportInputTOAllOfFromJSONTyped = DinosaurPassportInputTOAllOfFromJSONTyped;
function DinosaurPassportInputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'dinosaurTypeId': value.dinosaurTypeId,
        'dinosaurName': value.dinosaurName,
        'weight': value.weight,
        'height': value.height,
        'incubated': value.incubated,
        'revisionPeriod': value.revisionPeriod,
        'status': value.status,
    };
}
exports.DinosaurPassportInputTOAllOfToJSON = DinosaurPassportInputTOAllOfToJSON;
