"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function DinosaurPassportOutputTOAllOfFromJSON(json) {
    return DinosaurPassportOutputTOAllOfFromJSONTyped(json, false);
}
exports.DinosaurPassportOutputTOAllOfFromJSON = DinosaurPassportOutputTOAllOfFromJSON;
function DinosaurPassportOutputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'dinosaurType': !runtime_1.exists(json, 'dinosaurType') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['dinosaurType']),
        'dinosaurName': !runtime_1.exists(json, 'dinosaurName') ? undefined : json['dinosaurName'],
        'weight': !runtime_1.exists(json, 'weight') ? undefined : json['weight'],
        'height': !runtime_1.exists(json, 'height') ? undefined : json['height'],
        'incubated': !runtime_1.exists(json, 'incubated') ? undefined : json['incubated'],
        'revisionPeriod': !runtime_1.exists(json, 'revisionPeriod') ? undefined : json['revisionPeriod'],
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
    };
}
exports.DinosaurPassportOutputTOAllOfFromJSONTyped = DinosaurPassportOutputTOAllOfFromJSONTyped;
function DinosaurPassportOutputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'dinosaurType': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.dinosaurType),
        'dinosaurName': value.dinosaurName,
        'weight': value.weight,
        'height': value.height,
        'incubated': value.incubated,
        'revisionPeriod': value.revisionPeriod,
        'status': value.status,
    };
}
exports.DinosaurPassportOutputTOAllOfToJSON = DinosaurPassportOutputTOAllOfToJSON;
