"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var _1 = require("./");
function DocumentInputTOFromJSON(json) {
    return DocumentInputTOFromJSONTyped(json, false);
}
exports.DocumentInputTOFromJSON = DocumentInputTOFromJSON;
function DocumentInputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['documentType'] === 'AviaryPassportInputTO') {
            return _1.AviaryPassportInputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'DinosaurPassportInputTO') {
            return _1.DinosaurPassportInputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'TechnologicalMapInputTO') {
            return _1.TechnologicalMapInputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'ThemeZoneProjectInputTO') {
            return _1.ThemeZoneProjectInputTOFromJSONTyped(json, true);
        }
    }
    return {
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'documentType': json['documentType'],
    };
}
exports.DocumentInputTOFromJSONTyped = DocumentInputTOFromJSONTyped;
function DocumentInputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'description': value.description,
        'documentType': value.documentType,
    };
}
exports.DocumentInputTOToJSON = DocumentInputTOToJSON;
