"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var UserOutputTO_1 = require("./UserOutputTO");
var _1 = require("./");
/**
* @export
* @enum {string}
*/
var DocumentOutputTODocumentTypeEnum;
(function (DocumentOutputTODocumentTypeEnum) {
    DocumentOutputTODocumentTypeEnum["ThemeZoneProject"] = "THEME_ZONE_PROJECT";
    DocumentOutputTODocumentTypeEnum["DinosaurPassport"] = "DINOSAUR_PASSPORT";
    DocumentOutputTODocumentTypeEnum["TechnologicalMap"] = "TECHNOLOGICAL_MAP";
    DocumentOutputTODocumentTypeEnum["AviaryPassport"] = "AVIARY_PASSPORT";
    DocumentOutputTODocumentTypeEnum["ResearchData"] = "RESEARCH_DATA";
})(DocumentOutputTODocumentTypeEnum = exports.DocumentOutputTODocumentTypeEnum || (exports.DocumentOutputTODocumentTypeEnum = {}));
function DocumentOutputTOFromJSON(json) {
    return DocumentOutputTOFromJSONTyped(json, false);
}
exports.DocumentOutputTOFromJSON = DocumentOutputTOFromJSON;
function DocumentOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['documentType'] === 'AviaryPassportOutputTO') {
            return _1.AviaryPassportOutputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'DinosaurPassportOutputTO') {
            return _1.DinosaurPassportOutputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'ResearchDataOutputTO') {
            return _1.ResearchDataOutputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'TechnologicalMapOutputTO') {
            return _1.TechnologicalMapOutputTOFromJSONTyped(json, true);
        }
        if (json['documentType'] === 'ThemeZoneProjectOutputTO') {
            return _1.ThemeZoneProjectOutputTOFromJSONTyped(json, true);
        }
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'documentType': !runtime_1.exists(json, 'documentType') ? undefined : json['documentType'],
        'author': !runtime_1.exists(json, 'author') ? undefined : UserOutputTO_1.UserOutputTOFromJSON(json['author']),
        'lastUpdater': !runtime_1.exists(json, 'lastUpdater') ? undefined : UserOutputTO_1.UserOutputTOFromJSON(json['lastUpdater']),
        'created': !runtime_1.exists(json, 'created') ? undefined : json['created'],
        'lastUpdate': !runtime_1.exists(json, 'lastUpdate') ? undefined : json['lastUpdate'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
    };
}
exports.DocumentOutputTOFromJSONTyped = DocumentOutputTOFromJSONTyped;
function DocumentOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'documentType': value.documentType,
        'author': UserOutputTO_1.UserOutputTOToJSON(value.author),
        'lastUpdater': UserOutputTO_1.UserOutputTOToJSON(value.lastUpdater),
        'created': value.created,
        'lastUpdate': value.lastUpdate,
        'description': value.description,
    };
}
exports.DocumentOutputTOToJSON = DocumentOutputTOToJSON;
