"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var User_1 = require("./User");
/**
* @export
* @enum {string}
*/
var DocumentTypeEnum;
(function (DocumentTypeEnum) {
    DocumentTypeEnum["ThemeZoneProject"] = "THEME_ZONE_PROJECT";
    DocumentTypeEnum["DinosaurPassport"] = "DINOSAUR_PASSPORT";
    DocumentTypeEnum["TechnologicalMap"] = "TECHNOLOGICAL_MAP";
    DocumentTypeEnum["AviaryPassport"] = "AVIARY_PASSPORT";
    DocumentTypeEnum["ResearchData"] = "RESEARCH_DATA";
})(DocumentTypeEnum = exports.DocumentTypeEnum || (exports.DocumentTypeEnum = {}));
function DocumentFromJSON(json) {
    return DocumentFromJSONTyped(json, false);
}
exports.DocumentFromJSON = DocumentFromJSON;
function DocumentFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'type': !runtime_1.exists(json, 'type') ? undefined : json['type'],
        'author': !runtime_1.exists(json, 'author') ? undefined : User_1.UserFromJSON(json['author']),
        'lastUpdater': !runtime_1.exists(json, 'lastUpdater') ? undefined : User_1.UserFromJSON(json['lastUpdater']),
        'created': !runtime_1.exists(json, 'created') ? undefined : (new Date(json['created'])),
        'lastUpdate': !runtime_1.exists(json, 'lastUpdate') ? undefined : (new Date(json['lastUpdate'])),
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
    };
}
exports.DocumentFromJSONTyped = DocumentFromJSONTyped;
function DocumentToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'author': User_1.UserToJSON(value.author),
        'lastUpdater': User_1.UserToJSON(value.lastUpdater),
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'lastUpdate': value.lastUpdate === undefined ? undefined : (value.lastUpdate.toISOString()),
        'description': value.description,
    };
}
exports.DocumentToJSON = DocumentToJSON;
