/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './User';
/**
 *
 * @export
 * @interface Document
 */
export interface Document {
    /**
     *
     * @type {number}
     * @memberof Document
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    type?: DocumentTypeEnum;
    /**
     *
     * @type {User}
     * @memberof Document
     */
    author?: User;
    /**
     *
     * @type {User}
     * @memberof Document
     */
    lastUpdater?: User;
    /**
     *
     * @type {Date}
     * @memberof Document
     */
    created?: Date;
    /**
     *
     * @type {Date}
     * @memberof Document
     */
    lastUpdate?: Date;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    description?: string;
}
/**
* @export
* @enum {string}
*/
export declare enum DocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
export declare function DocumentFromJSON(json: any): Document;
export declare function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document;
export declare function DocumentToJSON(value?: Document | null): any;
