/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './Document';
import { UserOutputTO } from './UserOutputTO';
/**
 *
 * @export
 * @interface DocumentOutputTO
 */
export interface DocumentOutputTO {
    /**
     *
     * @type {number}
     * @memberof DocumentOutputTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof DocumentOutputTO
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof DocumentOutputTO
     */
    type?: DocumentOutputTOTypeEnum;
    /**
     *
     * @type {UserOutputTO}
     * @memberof DocumentOutputTO
     */
    author?: UserOutputTO;
    /**
     *
     * @type {UserOutputTO}
     * @memberof DocumentOutputTO
     */
    lastUpdater?: UserOutputTO;
    /**
     *
     * @type {Date}
     * @memberof DocumentOutputTO
     */
    created?: Date;
    /**
     *
     * @type {Date}
     * @memberof DocumentOutputTO
     */
    lastUpdate?: Date;
    /**
     *
     * @type {string}
     * @memberof DocumentOutputTO
     */
    description?: string;
    /**
     *
     * @type {Document}
     * @memberof DocumentOutputTO
     */
    baseFields?: Document;
}
/**
* @export
* @enum {string}
*/
export declare enum DocumentOutputTOTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
export declare function DocumentOutputTOFromJSON(json: any): DocumentOutputTO;
export declare function DocumentOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentOutputTO;
export declare function DocumentOutputTOToJSON(value?: DocumentOutputTO | null): any;
