"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
/**
* @export
* @enum {string}
*/
var FullUserInputTODepartmentEnum;
(function (FullUserInputTODepartmentEnum) {
    FullUserInputTODepartmentEnum["Research"] = "RESEARCH";
    FullUserInputTODepartmentEnum["Incubation"] = "INCUBATION";
    FullUserInputTODepartmentEnum["Security"] = "SECURITY";
    FullUserInputTODepartmentEnum["Administration"] = "ADMINISTRATION";
    FullUserInputTODepartmentEnum["Maintenance"] = "MAINTENANCE";
    FullUserInputTODepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(FullUserInputTODepartmentEnum = exports.FullUserInputTODepartmentEnum || (exports.FullUserInputTODepartmentEnum = {}));
function FullUserInputTOFromJSON(json) {
    return FullUserInputTOFromJSONTyped(json, false);
}
exports.FullUserInputTOFromJSON = FullUserInputTOFromJSON;
function FullUserInputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'username': json['username'],
        'password': json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'department': json['department'],
        'groupIds': !runtime_1.exists(json, 'groupIds') ? undefined : json['groupIds'],
    };
}
exports.FullUserInputTOFromJSONTyped = FullUserInputTOFromJSONTyped;
function FullUserInputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'username': value.username,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
        'groupIds': value.groupIds,
    };
}
exports.FullUserInputTOToJSON = FullUserInputTOToJSON;
