/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface FullUserInputTO
 */
export interface FullUserInputTO {
    /**
     *
     * @type {string}
     * @memberof FullUserInputTO
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserInputTO
     */
    password?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserInputTO
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserInputTO
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserInputTO
     */
    department: FullUserInputTODepartmentEnum;
    /**
     *
     * @type {Set<number>}
     * @memberof FullUserInputTO
     */
    groupIds?: Set<number>;
}
/**
* @export
* @enum {string}
*/
export declare enum FullUserInputTODepartmentEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    Security = "SECURITY",
    Administration = "ADMINISTRATION",
    Maintenance = "MAINTENANCE",
    Accommodation = "ACCOMMODATION"
}
export declare function FullUserInputTOFromJSON(json: any): FullUserInputTO;
export declare function FullUserInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullUserInputTO;
export declare function FullUserInputTOToJSON(value?: FullUserInputTO | null): any;
