/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleGroupTO } from './SimpleGroupTO';
/**
 *
 * @export
 * @interface FullUserOutputTO
 */
export interface FullUserOutputTO {
    /**
     *
     * @type {number}
     * @memberof FullUserOutputTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof FullUserOutputTO
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserOutputTO
     */
    password?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserOutputTO
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserOutputTO
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof FullUserOutputTO
     */
    department?: FullUserOutputTODepartmentEnum;
    /**
     *
     * @type {Array<SimpleGroupTO>}
     * @memberof FullUserOutputTO
     */
    groupIds?: Array<SimpleGroupTO>;
}
/**
* @export
* @enum {string}
*/
export declare enum FullUserOutputTODepartmentEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    Security = "SECURITY",
    Administration = "ADMINISTRATION",
    Maintenance = "MAINTENANCE",
    Accommodation = "ACCOMMODATION"
}
export declare function FullUserOutputTOFromJSON(json: any): FullUserOutputTO;
export declare function FullUserOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullUserOutputTO;
export declare function FullUserOutputTOToJSON(value?: FullUserOutputTO | null): any;
