"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleGroupTO_1 = require("./SimpleGroupTO");
/**
* @export
* @enum {string}
*/
var FullUserOutputTODepartmentEnum;
(function (FullUserOutputTODepartmentEnum) {
    FullUserOutputTODepartmentEnum["Research"] = "RESEARCH";
    FullUserOutputTODepartmentEnum["Incubation"] = "INCUBATION";
    FullUserOutputTODepartmentEnum["Security"] = "SECURITY";
    FullUserOutputTODepartmentEnum["Administration"] = "ADMINISTRATION";
    FullUserOutputTODepartmentEnum["Maintenance"] = "MAINTENANCE";
    FullUserOutputTODepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(FullUserOutputTODepartmentEnum = exports.FullUserOutputTODepartmentEnum || (exports.FullUserOutputTODepartmentEnum = {}));
function FullUserOutputTOFromJSON(json) {
    return FullUserOutputTOFromJSONTyped(json, false);
}
exports.FullUserOutputTOFromJSON = FullUserOutputTOFromJSON;
function FullUserOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'username': !runtime_1.exists(json, 'username') ? undefined : json['username'],
        'password': !runtime_1.exists(json, 'password') ? undefined : json['password'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'department': !runtime_1.exists(json, 'department') ? undefined : json['department'],
        'groupIds': !runtime_1.exists(json, 'groupIds') ? undefined : (json['groupIds'].map(SimpleGroupTO_1.SimpleGroupTOFromJSON)),
    };
}
exports.FullUserOutputTOFromJSONTyped = FullUserOutputTOFromJSONTyped;
function FullUserOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'username': value.username,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
        'groupIds': value.groupIds === undefined ? undefined : (value.groupIds.map(SimpleGroupTO_1.SimpleGroupTOToJSON)),
    };
}
exports.FullUserOutputTOToJSON = FullUserOutputTOToJSON;
