"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function IncubationTaskDTOAllOfFromJSON(json) {
    return IncubationTaskDTOAllOfFromJSONTyped(json, false);
}
exports.IncubationTaskDTOAllOfFromJSON = IncubationTaskDTOAllOfFromJSON;
function IncubationTaskDTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'dinosaurTypeId': !runtime_1.exists(json, 'dinosaurTypeId') ? undefined : json['dinosaurTypeId'],
    };
}
exports.IncubationTaskDTOAllOfFromJSONTyped = IncubationTaskDTOAllOfFromJSONTyped;
function IncubationTaskDTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'dinosaurTypeId': value.dinosaurTypeId,
    };
}
exports.IncubationTaskDTOAllOfToJSON = IncubationTaskDTOAllOfToJSON;
