"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
/* eslint-disable */
__export(require("./AssigneeDTO"));
__export(require("./AviaryPassportInputTO"));
__export(require("./AviaryPassportInputTOAllOf"));
__export(require("./AviaryPassportOutputTO"));
__export(require("./AviaryPassportOutputTOAllOf"));
__export(require("./AviaryTaskDTO"));
__export(require("./AviaryTaskDTOAllOf"));
__export(require("./DinosaurPassportInputTO"));
__export(require("./DinosaurPassportInputTOAllOf"));
__export(require("./DinosaurPassportOutputTO"));
__export(require("./DinosaurPassportOutputTOAllOf"));
__export(require("./DocumentInputTO"));
__export(require("./DocumentOutputTO"));
__export(require("./FullUserOutputTO"));
__export(require("./GroupOutputTO"));
__export(require("./IncubationTaskDTO"));
__export(require("./IncubationTaskDTOAllOf"));
__export(require("./LogEntry"));
__export(require("./ResearchDataInputTO"));
__export(require("./ResearchDataNameIdTO"));
__export(require("./ResearchDataOutputTO"));
__export(require("./ResearchDataOutputTOAllOf"));
__export(require("./ResearchTaskDTO"));
__export(require("./ResearchTaskDTOAllOf"));
__export(require("./RevisionEntryTO"));
__export(require("./SimpleEntityInputTO"));
__export(require("./SimpleEntityOutputTO"));
__export(require("./SimpleGroupTO"));
__export(require("./SimpleUserInfoTO"));
__export(require("./TaskPriorityTO"));
__export(require("./TaskTO"));
__export(require("./TechnologicalMapInputTO"));
__export(require("./TechnologicalMapInputTOAllOf"));
__export(require("./TechnologicalMapOutputTO"));
__export(require("./TechnologicalMapOutputTOAllOf"));
__export(require("./ThemeZoneElementOutputTO"));
__export(require("./ThemeZoneProjectInputTO"));
__export(require("./ThemeZoneProjectInputTOAllOf"));
__export(require("./ThemeZoneProjectOutputTO"));
__export(require("./ThemeZoneProjectOutputTOAllOf"));
__export(require("./UserIdInputTO"));
__export(require("./UserOutputTO"));
__export(require("./UserWithRolesTO"));
__export(require("./ValidationResponseTO"));
__export(require("./ViolationTO"));
