/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LogEntry
 */
export interface LogEntry {
    /**
     *
     * @type {number}
     * @memberof LogEntry
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof LogEntry
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof LogEntry
     */
    action?: string;
    /**
     *
     * @type {Date}
     * @memberof LogEntry
     */
    timestamp?: Date;
}
export declare function LogEntryFromJSON(json: any): LogEntry;
export declare function LogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogEntry;
export declare function LogEntryToJSON(value?: LogEntry | null): any;
