/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface MultipartFile
 */
export interface MultipartFile {
    /**
     *
     * @type {string}
     * @memberof MultipartFile
     */
    name?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof MultipartFile
     */
    bytes?: Array<string>;
    /**
     *
     * @type {boolean}
     * @memberof MultipartFile
     */
    empty?: boolean;
    /**
     *
     * @type {number}
     * @memberof MultipartFile
     */
    size?: number;
    /**
     *
     * @type {object}
     * @memberof MultipartFile
     */
    inputStream?: object;
    /**
     *
     * @type {string}
     * @memberof MultipartFile
     */
    contentType?: string;
    /**
     *
     * @type {string}
     * @memberof MultipartFile
     */
    originalFilename?: string;
}
export declare function MultipartFileFromJSON(json: any): MultipartFile;
export declare function MultipartFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipartFile;
export declare function MultipartFileToJSON(value?: MultipartFile | null): any;
