/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface ResearchDataOutputTOAllOf
 */
export interface ResearchDataOutputTOAllOf {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof ResearchDataOutputTOAllOf
     */
    research?: SimpleEntityOutputTO;
    /**
     *
     * @type {Array<string>}
     * @memberof ResearchDataOutputTOAllOf
     */
    attachment?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ResearchDataOutputTOAllOf
     */
    attachmentName?: string;
}
export declare function ResearchDataOutputTOAllOfFromJSON(json: any): ResearchDataOutputTOAllOf;
export declare function ResearchDataOutputTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchDataOutputTOAllOf;
export declare function ResearchDataOutputTOAllOfToJSON(value?: ResearchDataOutputTOAllOf | null): any;
