/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentOutputTO } from './DocumentOutputTO';
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface ResearchDataOutputTO
 */
export interface ResearchDataOutputTO extends DocumentOutputTO {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof ResearchDataOutputTO
     */
    research?: SimpleEntityOutputTO;
    /**
     *
     * @type {Array<string>}
     * @memberof ResearchDataOutputTO
     */
    attachment?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ResearchDataOutputTO
     */
    attachmentName?: string;
}
export declare function ResearchDataOutputTOFromJSON(json: any): ResearchDataOutputTO;
export declare function ResearchDataOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchDataOutputTO;
export declare function ResearchDataOutputTOToJSON(value?: ResearchDataOutputTO | null): any;
