"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var DocumentOutputTO_1 = require("./DocumentOutputTO");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function ResearchDataOutputTOFromJSON(json) {
    return ResearchDataOutputTOFromJSONTyped(json, false);
}
exports.ResearchDataOutputTOFromJSON = ResearchDataOutputTOFromJSON;
function ResearchDataOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return __assign({}, DocumentOutputTO_1.DocumentOutputTOFromJSONTyped(json, ignoreDiscriminator), { 'research': !runtime_1.exists(json, 'research') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['research']), 'attachment': !runtime_1.exists(json, 'attachment') ? undefined : json['attachment'], 'attachmentName': !runtime_1.exists(json, 'attachmentName') ? undefined : json['attachmentName'] });
}
exports.ResearchDataOutputTOFromJSONTyped = ResearchDataOutputTOFromJSONTyped;
function ResearchDataOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return __assign({}, DocumentOutputTO_1.DocumentOutputTOToJSON(value), { 'research': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.research), 'attachment': value.attachment, 'attachmentName': value.attachmentName });
}
exports.ResearchDataOutputTOToJSON = ResearchDataOutputTOToJSON;
