/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ResearchTaskDTOAllOf
 */
export interface ResearchTaskDTOAllOf {
    /**
     *
     * @type {string}
     * @memberof ResearchTaskDTOAllOf
     */
    purpose: string;
}
export declare function ResearchTaskDTOAllOfFromJSON(json: any): ResearchTaskDTOAllOf;
export declare function ResearchTaskDTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchTaskDTOAllOf;
export declare function ResearchTaskDTOAllOfToJSON(value?: ResearchTaskDTOAllOf | null): any;
