"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
function ResearchTaskDTOAllOfFromJSON(json) {
    return ResearchTaskDTOAllOfFromJSONTyped(json, false);
}
exports.ResearchTaskDTOAllOfFromJSON = ResearchTaskDTOAllOfFromJSON;
function ResearchTaskDTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'purpose': json['purpose'],
    };
}
exports.ResearchTaskDTOAllOfFromJSONTyped = ResearchTaskDTOAllOfFromJSONTyped;
function ResearchTaskDTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'purpose': value.purpose,
    };
}
exports.ResearchTaskDTOAllOfToJSON = ResearchTaskDTOAllOfToJSON;
