"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function ResearchDataOutputTOAllOfFromJSON(json) {
    return ResearchDataOutputTOAllOfFromJSONTyped(json, false);
}
exports.ResearchDataOutputTOAllOfFromJSON = ResearchDataOutputTOAllOfFromJSON;
function ResearchDataOutputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'research': !runtime_1.exists(json, 'research') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['research']),
        'attachment': !runtime_1.exists(json, 'attachment') ? undefined : json['attachment'],
        'attachmentName': !runtime_1.exists(json, 'attachmentName') ? undefined : json['attachmentName'],
    };
}
exports.ResearchDataOutputTOAllOfFromJSONTyped = ResearchDataOutputTOAllOfFromJSONTyped;
function ResearchDataOutputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'research': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.research),
        'attachment': value.attachment,
        'attachmentName': value.attachmentName,
    };
}
exports.ResearchDataOutputTOAllOfToJSON = ResearchDataOutputTOAllOfToJSON;
