/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface RevisionEntryTO
 */
export interface RevisionEntryTO {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof RevisionEntryTO
     */
    entity?: SimpleEntityOutputTO;
    /**
     *
     * @type {number}
     * @memberof RevisionEntryTO
     */
    revisionDate?: number;
}
export declare function RevisionEntryTOFromJSON(json: any): RevisionEntryTO;
export declare function RevisionEntryTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionEntryTO;
export declare function RevisionEntryTOToJSON(value?: RevisionEntryTO | null): any;
