/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ScheduleItem
 */
export interface ScheduleItem {
    /**
     *
     * @type {Date}
     * @memberof ScheduleItem
     */
    date?: Date;
    /**
     *
     * @type {string}
     * @memberof ScheduleItem
     */
    name?: string;
}
export declare function ScheduleItemFromJSON(json: any): ScheduleItem;
export declare function ScheduleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleItem;
export declare function ScheduleItemToJSON(value?: ScheduleItem | null): any;
