"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
function ScheduleInputTOFromJSON(json) {
    return ScheduleInputTOFromJSONTyped(json, false);
}
exports.ScheduleInputTOFromJSON = ScheduleInputTOFromJSON;
function ScheduleInputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'maxDate': (new Date(json['maxDate'])),
    };
}
exports.ScheduleInputTOFromJSONTyped = ScheduleInputTOFromJSONTyped;
function ScheduleInputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'maxDate': (value.maxDate.toISOString().substr(0, 10)),
    };
}
exports.ScheduleInputTOToJSON = ScheduleInputTOToJSON;
