"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
/**
* @export
* @enum {string}
*/
var SimpleUserInfoTODepartmentEnum;
(function (SimpleUserInfoTODepartmentEnum) {
    SimpleUserInfoTODepartmentEnum["Research"] = "RESEARCH";
    SimpleUserInfoTODepartmentEnum["Incubation"] = "INCUBATION";
    SimpleUserInfoTODepartmentEnum["Security"] = "SECURITY";
    SimpleUserInfoTODepartmentEnum["Administration"] = "ADMINISTRATION";
    SimpleUserInfoTODepartmentEnum["Maintenance"] = "MAINTENANCE";
    SimpleUserInfoTODepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(SimpleUserInfoTODepartmentEnum = exports.SimpleUserInfoTODepartmentEnum || (exports.SimpleUserInfoTODepartmentEnum = {}));
function SimpleUserInfoTOFromJSON(json) {
    return SimpleUserInfoTOFromJSONTyped(json, false);
}
exports.SimpleUserInfoTOFromJSON = SimpleUserInfoTOFromJSON;
function SimpleUserInfoTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'username': !runtime_1.exists(json, 'username') ? undefined : json['username'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'department': !runtime_1.exists(json, 'department') ? undefined : json['department'],
    };
}
exports.SimpleUserInfoTOFromJSONTyped = SimpleUserInfoTOFromJSONTyped;
function SimpleUserInfoTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'username': value.username,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
    };
}
exports.SimpleUserInfoTOToJSON = SimpleUserInfoTOToJSON;
