/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SimpleEntityOutputTO
 */
export interface SimpleEntityOutputTO {
    /**
     *
     * @type {number}
     * @memberof SimpleEntityOutputTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof SimpleEntityOutputTO
     */
    name?: string;
}
export declare function SimpleEntityOutputTOFromJSON(json: any): SimpleEntityOutputTO;
export declare function SimpleEntityOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleEntityOutputTO;
export declare function SimpleEntityOutputTOToJSON(value?: SimpleEntityOutputTO | null): any;
