"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
function SimpleEntityInputTOFromJSON(json) {
    return SimpleEntityInputTOFromJSONTyped(json, false);
}
exports.SimpleEntityInputTOFromJSON = SimpleEntityInputTOFromJSON;
function SimpleEntityInputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': json['name'],
    };
}
exports.SimpleEntityInputTOFromJSONTyped = SimpleEntityInputTOFromJSONTyped;
function SimpleEntityInputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
    };
}
exports.SimpleEntityInputTOToJSON = SimpleEntityInputTOToJSON;
