/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SimpleUserInfoTO
 */
export interface SimpleUserInfoTO {
    /**
     *
     * @type {number}
     * @memberof SimpleUserInfoTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof SimpleUserInfoTO
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof SimpleUserInfoTO
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof SimpleUserInfoTO
     */
    lastName?: string;
}
export declare function SimpleUserInfoTOFromJSON(json: any): SimpleUserInfoTO;
export declare function SimpleUserInfoTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUserInfoTO;
export declare function SimpleUserInfoTOToJSON(value?: SimpleUserInfoTO | null): any;
