/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SimpleEntityInputTO
 */
export interface SimpleEntityInputTO {
    /**
     *
     * @type {string}
     * @memberof SimpleEntityInputTO
     */
    name: string;
}
export declare function SimpleEntityInputTOFromJSON(json: any): SimpleEntityInputTO;
export declare function SimpleEntityInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleEntityInputTO;
export declare function SimpleEntityInputTOToJSON(value?: SimpleEntityInputTO | null): any;
