"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var TaskPriority_1 = require("./TaskPriority");
var User_1 = require("./User");
/**
* @export
* @enum {string}
*/
var TaskTaskTypeEnum;
(function (TaskTaskTypeEnum) {
    TaskTaskTypeEnum["Research"] = "RESEARCH";
    TaskTaskTypeEnum["Incubation"] = "INCUBATION";
    TaskTaskTypeEnum["AviaryCreation"] = "AVIARY_CREATION";
})(TaskTaskTypeEnum = exports.TaskTaskTypeEnum || (exports.TaskTaskTypeEnum = {})); /**
* @export
* @enum {string}
*/
var TaskStatusEnum;
(function (TaskStatusEnum) {
    TaskStatusEnum["Closed"] = "CLOSED";
    TaskStatusEnum["Resolved"] = "RESOLVED";
    TaskStatusEnum["InProgress"] = "IN_PROGRESS";
    TaskStatusEnum["Open"] = "OPEN";
})(TaskStatusEnum = exports.TaskStatusEnum || (exports.TaskStatusEnum = {}));
function TaskFromJSON(json) {
    return TaskFromJSONTyped(json, false);
}
exports.TaskFromJSON = TaskFromJSON;
function TaskFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'taskType': !runtime_1.exists(json, 'taskType') ? undefined : json['taskType'],
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
        'created': !runtime_1.exists(json, 'created') ? undefined : (new Date(json['created'])),
        'priority': !runtime_1.exists(json, 'priority') ? undefined : TaskPriority_1.TaskPriorityFromJSON(json['priority']),
        'createdBy': !runtime_1.exists(json, 'createdBy') ? undefined : User_1.UserFromJSON(json['createdBy']),
        'lastUpdated': !runtime_1.exists(json, 'lastUpdated') ? undefined : (new Date(json['lastUpdated'])),
        'lastUpdater': !runtime_1.exists(json, 'lastUpdater') ? undefined : User_1.UserFromJSON(json['lastUpdater']),
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'assignee': !runtime_1.exists(json, 'assignee') ? undefined : User_1.UserFromJSON(json['assignee']),
    };
}
exports.TaskFromJSONTyped = TaskFromJSONTyped;
function TaskToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'taskType': value.taskType,
        'status': value.status,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'priority': TaskPriority_1.TaskPriorityToJSON(value.priority),
        'createdBy': User_1.UserToJSON(value.createdBy),
        'lastUpdated': value.lastUpdated === undefined ? undefined : (value.lastUpdated.toISOString()),
        'lastUpdater': User_1.UserToJSON(value.lastUpdater),
        'description': value.description,
        'assignee': User_1.UserToJSON(value.assignee),
    };
}
exports.TaskToJSON = TaskToJSON;
