/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPriority } from './TaskPriority';
import { User } from './User';
/**
 *
 * @export
 * @interface Task
 */
export interface Task {
    /**
     *
     * @type {number}
     * @memberof Task
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    taskType?: TaskTaskTypeEnum;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    status?: TaskStatusEnum;
    /**
     *
     * @type {Date}
     * @memberof Task
     */
    created?: Date;
    /**
     *
     * @type {TaskPriority}
     * @memberof Task
     */
    priority?: TaskPriority;
    /**
     *
     * @type {User}
     * @memberof Task
     */
    createdBy?: User;
    /**
     *
     * @type {Date}
     * @memberof Task
     */
    lastUpdated?: Date;
    /**
     *
     * @type {User}
     * @memberof Task
     */
    lastUpdater?: User;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    description?: string;
    /**
     *
     * @type {User}
     * @memberof Task
     */
    assignee?: User;
}
/**
* @export
* @enum {string}
*/
export declare enum TaskTaskTypeEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    AviaryCreation = "AVIARY_CREATION"
} /**
* @export
* @enum {string}
*/
export declare enum TaskStatusEnum {
    Closed = "CLOSED",
    Resolved = "RESOLVED",
    InProgress = "IN_PROGRESS",
    Open = "OPEN"
}
export declare function TaskFromJSON(json: any): Task;
export declare function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task;
export declare function TaskToJSON(value?: Task | null): any;
