/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskTO
 */
export interface TaskTO {
    /**
     *
     * @type {number}
     * @memberof TaskTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof TaskTO
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof TaskTO
     */
    currentState?: TaskTOCurrentStateEnum;
    /**
     *
     * @type {Array<string>}
     * @memberof TaskTO
     */
    possibleNextStates?: Array<TaskTOPossibleNextStatesEnum>;
    /**
     *
     * @type {string}
     * @memberof TaskTO
     */
    taskType: TaskTOTaskTypeEnum;
    /**
     *
     * @type {Date}
     * @memberof TaskTO
     */
    created?: Date;
    /**
     *
     * @type {Date}
     * @memberof TaskTO
     */
    lastUpdated?: Date;
    /**
     *
     * @type {number}
     * @memberof TaskTO
     */
    taskPriorityId?: number;
    /**
     *
     * @type {number}
     * @memberof TaskTO
     */
    createdById?: number;
    /**
     *
     * @type {number}
     * @memberof TaskTO
     */
    lastUpdaterId?: number;
    /**
     *
     * @type {number}
     * @memberof TaskTO
     */
    assigneeId?: number;
    /**
     *
     * @type {string}
     * @memberof TaskTO
     */
    description?: string;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof TaskTO
     */
    additionalParams?: {
        [key: string]: object;
    };
}
/**
* @export
* @enum {string}
*/
export declare enum TaskTOCurrentStateEnum {
    Closed = "CLOSED",
    Resolved = "RESOLVED",
    InProgress = "IN_PROGRESS",
    Open = "OPEN"
} /**
* @export
* @enum {string}
*/
export declare enum TaskTOPossibleNextStatesEnum {
    Closed = "CLOSED",
    Resolved = "RESOLVED",
    InProgress = "IN_PROGRESS",
    Open = "OPEN"
} /**
* @export
* @enum {string}
*/
export declare enum TaskTOTaskTypeEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    AviaryCreation = "AVIARY_CREATION"
}
export declare function TaskTOFromJSON(json: any): TaskTO;
export declare function TaskTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskTO;
export declare function TaskTOToJSON(value?: TaskTO | null): any;
