"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function TaskPriorityFromJSON(json) {
    return TaskPriorityFromJSONTyped(json, false);
}
exports.TaskPriorityFromJSON = TaskPriorityFromJSON;
function TaskPriorityFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'absolutePriority': !runtime_1.exists(json, 'absolutePriority') ? undefined : json['absolutePriority'],
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
    };
}
exports.TaskPriorityFromJSONTyped = TaskPriorityFromJSONTyped;
function TaskPriorityToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'absolutePriority': value.absolutePriority,
        'name': value.name,
    };
}
exports.TaskPriorityToJSON = TaskPriorityToJSON;
