/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskPriorityTO
 */
export interface TaskPriorityTO {
    /**
     *
     * @type {number}
     * @memberof TaskPriorityTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof TaskPriorityTO
     */
    name?: string;
}
export declare function TaskPriorityTOFromJSON(json: any): TaskPriorityTO;
export declare function TaskPriorityTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskPriorityTO;
export declare function TaskPriorityTOToJSON(value?: TaskPriorityTO | null): any;
