/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskPriority
 */
export interface TaskPriority {
    /**
     *
     * @type {number}
     * @memberof TaskPriority
     */
    id?: number;
    /**
     *
     * @type {number}
     * @memberof TaskPriority
     */
    absolutePriority?: number;
    /**
     *
     * @type {string}
     * @memberof TaskPriority
     */
    name?: string;
}
export declare function TaskPriorityFromJSON(json: any): TaskPriority;
export declare function TaskPriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskPriority;
export declare function TaskPriorityToJSON(value?: TaskPriority | null): any;
