/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentInputTO } from './DocumentInputTO';
/**
 *
 * @export
 * @interface TechnologicalMapInputTO
 */
export interface TechnologicalMapInputTO extends DocumentInputTO {
    /**
     *
     * @type {number}
     * @memberof TechnologicalMapInputTO
     */
    dinosaurTypeId: number;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapInputTO
     */
    incubationSteps?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapInputTO
     */
    eggCreationSteps?: Array<string>;
}
export declare function TechnologicalMapInputTOFromJSON(json: any): TechnologicalMapInputTO;
export declare function TechnologicalMapInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologicalMapInputTO;
export declare function TechnologicalMapInputTOToJSON(value?: TechnologicalMapInputTO | null): any;
