/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface TechnologicalMapOutputTOAllOf
 */
export interface TechnologicalMapOutputTOAllOf {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof TechnologicalMapOutputTOAllOf
     */
    dinosaurType?: SimpleEntityOutputTO;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapOutputTOAllOf
     */
    incubationSteps?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapOutputTOAllOf
     */
    eggCreationSteps?: Array<string>;
}
export declare function TechnologicalMapOutputTOAllOfFromJSON(json: any): TechnologicalMapOutputTOAllOf;
export declare function TechnologicalMapOutputTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologicalMapOutputTOAllOf;
export declare function TechnologicalMapOutputTOAllOfToJSON(value?: TechnologicalMapOutputTOAllOf | null): any;
