/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentOutputTO } from './DocumentOutputTO';
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface TechnologicalMapOutputTO
 */
export interface TechnologicalMapOutputTO extends DocumentOutputTO {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof TechnologicalMapOutputTO
     */
    dinosaurType?: SimpleEntityOutputTO;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapOutputTO
     */
    incubationSteps?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof TechnologicalMapOutputTO
     */
    eggCreationSteps?: Array<string>;
}
export declare function TechnologicalMapOutputTOFromJSON(json: any): TechnologicalMapOutputTO;
export declare function TechnologicalMapOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnologicalMapOutputTO;
export declare function TechnologicalMapOutputTOToJSON(value?: TechnologicalMapOutputTO | null): any;
