"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleEntityOutputTO_1 = require("./SimpleEntityOutputTO");
function ThemeZoneElementOutputTOFromJSON(json) {
    return ThemeZoneElementOutputTOFromJSONTyped(json, false);
}
exports.ThemeZoneElementOutputTOFromJSON = ThemeZoneElementOutputTOFromJSON;
function ThemeZoneElementOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'type': !runtime_1.exists(json, 'type') ? undefined : SimpleEntityOutputTO_1.SimpleEntityOutputTOFromJSON(json['type']),
        'number': !runtime_1.exists(json, 'number') ? undefined : json['number'],
    };
}
exports.ThemeZoneElementOutputTOFromJSONTyped = ThemeZoneElementOutputTOFromJSONTyped;
function ThemeZoneElementOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'type': SimpleEntityOutputTO_1.SimpleEntityOutputTOToJSON(value.type),
        'number': value.number,
    };
}
exports.ThemeZoneElementOutputTOToJSON = ThemeZoneElementOutputTOToJSON;
