/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ThemeZoneProjectInputTOAllOf
 */
export interface ThemeZoneProjectInputTOAllOf {
    /**
     *
     * @type {string}
     * @memberof ThemeZoneProjectInputTOAllOf
     */
    projectName?: string;
    /**
     *
     * @type {number}
     * @memberof ThemeZoneProjectInputTOAllOf
     */
    managerId: number;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTOAllOf
     */
    dinosaurs?: {
        [key: string]: number;
    };
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTOAllOf
     */
    aviaries?: {
        [key: string]: number;
    };
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTOAllOf
     */
    decorations?: {
        [key: string]: number;
    };
}
export declare function ThemeZoneProjectInputTOAllOfFromJSON(json: any): ThemeZoneProjectInputTOAllOf;
export declare function ThemeZoneProjectInputTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeZoneProjectInputTOAllOf;
export declare function ThemeZoneProjectInputTOAllOfToJSON(value?: ThemeZoneProjectInputTOAllOf | null): any;
