/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentInputTO } from './DocumentInputTO';
/**
 *
 * @export
 * @interface ThemeZoneProjectInputTO
 */
export interface ThemeZoneProjectInputTO extends DocumentInputTO {
    /**
     *
     * @type {string}
     * @memberof ThemeZoneProjectInputTO
     */
    projectName?: string;
    /**
     *
     * @type {number}
     * @memberof ThemeZoneProjectInputTO
     */
    managerId: number;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTO
     */
    dinosaurs?: {
        [key: string]: number;
    };
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTO
     */
    aviaries?: {
        [key: string]: number;
    };
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof ThemeZoneProjectInputTO
     */
    decorations?: {
        [key: string]: number;
    };
}
export declare function ThemeZoneProjectInputTOFromJSON(json: any): ThemeZoneProjectInputTO;
export declare function ThemeZoneProjectInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeZoneProjectInputTO;
export declare function ThemeZoneProjectInputTOToJSON(value?: ThemeZoneProjectInputTO | null): any;
