/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentOutputTO } from './DocumentOutputTO';
import { ThemeZoneElementOutputTO } from './ThemeZoneElementOutputTO';
import { UserOutputTO } from './UserOutputTO';
/**
 *
 * @export
 * @interface ThemeZoneProjectOutputTO
 */
export interface ThemeZoneProjectOutputTO extends DocumentOutputTO {
    /**
     *
     * @type {string}
     * @memberof ThemeZoneProjectOutputTO
     */
    projectName?: string;
    /**
     *
     * @type {UserOutputTO}
     * @memberof ThemeZoneProjectOutputTO
     */
    manager?: UserOutputTO;
    /**
     *
     * @type {Array<ThemeZoneElementOutputTO>}
     * @memberof ThemeZoneProjectOutputTO
     */
    dinosaurs?: Array<ThemeZoneElementOutputTO>;
    /**
     *
     * @type {Array<ThemeZoneElementOutputTO>}
     * @memberof ThemeZoneProjectOutputTO
     */
    aviaries?: Array<ThemeZoneElementOutputTO>;
    /**
     *
     * @type {Array<ThemeZoneElementOutputTO>}
     * @memberof ThemeZoneProjectOutputTO
     */
    decorations?: Array<ThemeZoneElementOutputTO>;
}
export declare function ThemeZoneProjectOutputTOFromJSON(json: any): ThemeZoneProjectOutputTO;
export declare function ThemeZoneProjectOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeZoneProjectOutputTO;
export declare function ThemeZoneProjectOutputTOToJSON(value?: ThemeZoneProjectOutputTO | null): any;
