/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEntityOutputTO } from './SimpleEntityOutputTO';
/**
 *
 * @export
 * @interface ThemeZoneElementOutputTO
 */
export interface ThemeZoneElementOutputTO {
    /**
     *
     * @type {SimpleEntityOutputTO}
     * @memberof ThemeZoneElementOutputTO
     */
    type?: SimpleEntityOutputTO;
    /**
     *
     * @type {number}
     * @memberof ThemeZoneElementOutputTO
     */
    number?: number;
}
export declare function ThemeZoneElementOutputTOFromJSON(json: any): ThemeZoneElementOutputTO;
export declare function ThemeZoneElementOutputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeZoneElementOutputTO;
export declare function ThemeZoneElementOutputTOToJSON(value?: ThemeZoneElementOutputTO | null): any;
