"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function ThemeZoneProjectInputTOAllOfFromJSON(json) {
    return ThemeZoneProjectInputTOAllOfFromJSONTyped(json, false);
}
exports.ThemeZoneProjectInputTOAllOfFromJSON = ThemeZoneProjectInputTOAllOfFromJSON;
function ThemeZoneProjectInputTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'projectName': !runtime_1.exists(json, 'projectName') ? undefined : json['projectName'],
        'managerId': json['managerId'],
        'dinosaurs': !runtime_1.exists(json, 'dinosaurs') ? undefined : json['dinosaurs'],
        'aviaries': !runtime_1.exists(json, 'aviaries') ? undefined : json['aviaries'],
        'decorations': !runtime_1.exists(json, 'decorations') ? undefined : json['decorations'],
    };
}
exports.ThemeZoneProjectInputTOAllOfFromJSONTyped = ThemeZoneProjectInputTOAllOfFromJSONTyped;
function ThemeZoneProjectInputTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'projectName': value.projectName,
        'managerId': value.managerId,
        'dinosaurs': value.dinosaurs,
        'aviaries': value.aviaries,
        'decorations': value.decorations,
    };
}
exports.ThemeZoneProjectInputTOAllOfToJSON = ThemeZoneProjectInputTOAllOfToJSON;
