/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateUserTO
 */
export interface UpdateUserTO {
    /**
     *
     * @type {string}
     * @memberof UpdateUserTO
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserTO
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserTO
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserTO
     */
    department: UpdateUserTODepartmentEnum;
    /**
     *
     * @type {Set<number>}
     * @memberof UpdateUserTO
     */
    groupIds?: Set<number>;
}
/**
* @export
* @enum {string}
*/
export declare enum UpdateUserTODepartmentEnum {
    Research = "RESEARCH",
    Incubation = "INCUBATION",
    Security = "SECURITY",
    Administration = "ADMINISTRATION",
    Maintenance = "MAINTENANCE",
    Accommodation = "ACCOMMODATION"
}
export declare function UpdateUserTOFromJSON(json: any): UpdateUserTO;
export declare function UpdateUserTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserTO;
export declare function UpdateUserTOToJSON(value?: UpdateUserTO | null): any;
