"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var SimpleGroupTO_1 = require("./SimpleGroupTO");
/**
* @export
* @enum {string}
*/
var UserWithRolesTODepartmentEnum;
(function (UserWithRolesTODepartmentEnum) {
    UserWithRolesTODepartmentEnum["Research"] = "RESEARCH";
    UserWithRolesTODepartmentEnum["Incubation"] = "INCUBATION";
    UserWithRolesTODepartmentEnum["Security"] = "SECURITY";
    UserWithRolesTODepartmentEnum["Administration"] = "ADMINISTRATION";
    UserWithRolesTODepartmentEnum["Maintenance"] = "MAINTENANCE";
    UserWithRolesTODepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(UserWithRolesTODepartmentEnum = exports.UserWithRolesTODepartmentEnum || (exports.UserWithRolesTODepartmentEnum = {})); /**
* @export
* @enum {string}
*/
var UserWithRolesTORolesEnum;
(function (UserWithRolesTORolesEnum) {
    UserWithRolesTORolesEnum["DocumentReader"] = "DOCUMENT_READER";
    UserWithRolesTORolesEnum["DinosaurPassportReader"] = "DINOSAUR_PASSPORT_READER";
    UserWithRolesTORolesEnum["AviaryPassportReader"] = "AVIARY_PASSPORT_READER";
    UserWithRolesTORolesEnum["ThemeZoneProjectReader"] = "THEME_ZONE_PROJECT_READER";
    UserWithRolesTORolesEnum["TechnologicalMapReader"] = "TECHNOLOGICAL_MAP_READER";
    UserWithRolesTORolesEnum["ResearchDataReader"] = "RESEARCH_DATA_READER";
    UserWithRolesTORolesEnum["DocumentWriter"] = "DOCUMENT_WRITER";
    UserWithRolesTORolesEnum["DinosaurPassportWriter"] = "DINOSAUR_PASSPORT_WRITER";
    UserWithRolesTORolesEnum["AviaryPassportWriter"] = "AVIARY_PASSPORT_WRITER";
    UserWithRolesTORolesEnum["ThemeZoneProjectWriter"] = "THEME_ZONE_PROJECT_WRITER";
    UserWithRolesTORolesEnum["TechnologicalMapWriter"] = "TECHNOLOGICAL_MAP_WRITER";
    UserWithRolesTORolesEnum["ResearchDataWriter"] = "RESEARCH_DATA_WRITER";
    UserWithRolesTORolesEnum["TaskReader"] = "TASK_READER";
    UserWithRolesTORolesEnum["IncubationTaskReader"] = "INCUBATION_TASK_READER";
    UserWithRolesTORolesEnum["AviaryBuildingTaskReader"] = "AVIARY_BUILDING_TASK_READER";
    UserWithRolesTORolesEnum["ResearchTaskReader"] = "RESEARCH_TASK_READER";
    UserWithRolesTORolesEnum["TaskWriter"] = "TASK_WRITER";
    UserWithRolesTORolesEnum["IncubationTaskWriter"] = "INCUBATION_TASK_WRITER";
    UserWithRolesTORolesEnum["AviaryBuildingTaskWriter"] = "AVIARY_BUILDING_TASK_WRITER";
    UserWithRolesTORolesEnum["ResearchTaskWriter"] = "RESEARCH_TASK_WRITER";
    UserWithRolesTORolesEnum["SecurityReader"] = "SECURITY_READER";
    UserWithRolesTORolesEnum["SecurityWriter"] = "SECURITY_WRITER";
    UserWithRolesTORolesEnum["Admin"] = "ADMIN";
})(UserWithRolesTORolesEnum = exports.UserWithRolesTORolesEnum || (exports.UserWithRolesTORolesEnum = {}));
function UserWithRolesTOFromJSON(json) {
    return UserWithRolesTOFromJSONTyped(json, false);
}
exports.UserWithRolesTOFromJSON = UserWithRolesTOFromJSON;
function UserWithRolesTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'avatarSrc': !runtime_1.exists(json, 'avatarSrc') ? undefined : json['avatarSrc'],
        'username': !runtime_1.exists(json, 'username') ? undefined : json['username'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'department': !runtime_1.exists(json, 'department') ? undefined : json['department'],
        'roles': !runtime_1.exists(json, 'roles') ? undefined : json['roles'],
        'groups': !runtime_1.exists(json, 'groups') ? undefined : (json['groups'].map(SimpleGroupTO_1.SimpleGroupTOFromJSON)),
    };
}
exports.UserWithRolesTOFromJSONTyped = UserWithRolesTOFromJSONTyped;
function UserWithRolesTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'avatarSrc': value.avatarSrc,
        'username': value.username,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
        'roles': value.roles,
        'groups': value.groups === undefined ? undefined : (value.groups.map(SimpleGroupTO_1.SimpleGroupTOToJSON)),
    };
}
exports.UserWithRolesTOToJSON = UserWithRolesTOToJSON;
