"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
/**
* @export
* @enum {string}
*/
var UserOutputTODepartmentEnum;
(function (UserOutputTODepartmentEnum) {
    UserOutputTODepartmentEnum["Research"] = "RESEARCH";
    UserOutputTODepartmentEnum["Incubation"] = "INCUBATION";
    UserOutputTODepartmentEnum["Security"] = "SECURITY";
    UserOutputTODepartmentEnum["Administration"] = "ADMINISTRATION";
    UserOutputTODepartmentEnum["Maintenance"] = "MAINTENANCE";
    UserOutputTODepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(UserOutputTODepartmentEnum = exports.UserOutputTODepartmentEnum || (exports.UserOutputTODepartmentEnum = {}));
function UserOutputTOFromJSON(json) {
    return UserOutputTOFromJSONTyped(json, false);
}
exports.UserOutputTOFromJSON = UserOutputTOFromJSON;
function UserOutputTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'username': !runtime_1.exists(json, 'username') ? undefined : json['username'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'department': !runtime_1.exists(json, 'department') ? undefined : json['department'],
    };
}
exports.UserOutputTOFromJSONTyped = UserOutputTOFromJSONTyped;
function UserOutputTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'username': value.username,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
    };
}
exports.UserOutputTOToJSON = UserOutputTOToJSON;
