"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
var Group_1 = require("./Group");
var Task_1 = require("./Task");
/**
* @export
* @enum {string}
*/
var UserDepartmentEnum;
(function (UserDepartmentEnum) {
    UserDepartmentEnum["Research"] = "RESEARCH";
    UserDepartmentEnum["Incubation"] = "INCUBATION";
    UserDepartmentEnum["Security"] = "SECURITY";
    UserDepartmentEnum["Administration"] = "ADMINISTRATION";
    UserDepartmentEnum["Maintenance"] = "MAINTENANCE";
    UserDepartmentEnum["Accommodation"] = "ACCOMMODATION";
})(UserDepartmentEnum = exports.UserDepartmentEnum || (exports.UserDepartmentEnum = {})); /**
* @export
* @enum {string}
*/
var UserRolesEnum;
(function (UserRolesEnum) {
    UserRolesEnum["DocumentReader"] = "DOCUMENT_READER";
    UserRolesEnum["DinosaurPassportReader"] = "DINOSAUR_PASSPORT_READER";
    UserRolesEnum["AviaryPassportReader"] = "AVIARY_PASSPORT_READER";
    UserRolesEnum["ThemeZoneProjectReader"] = "THEME_ZONE_PROJECT_READER";
    UserRolesEnum["TechnologicalMapReader"] = "TECHNOLOGICAL_MAP_READER";
    UserRolesEnum["ResearchDataReader"] = "RESEARCH_DATA_READER";
    UserRolesEnum["DocumentWriter"] = "DOCUMENT_WRITER";
    UserRolesEnum["DinosaurPassportWriter"] = "DINOSAUR_PASSPORT_WRITER";
    UserRolesEnum["AviaryPassportWriter"] = "AVIARY_PASSPORT_WRITER";
    UserRolesEnum["ThemeZoneProjectWriter"] = "THEME_ZONE_PROJECT_WRITER";
    UserRolesEnum["TechnologicalMapWriter"] = "TECHNOLOGICAL_MAP_WRITER";
    UserRolesEnum["ResearchDataWriter"] = "RESEARCH_DATA_WRITER";
    UserRolesEnum["TaskReader"] = "TASK_READER";
    UserRolesEnum["IncubationTaskReader"] = "INCUBATION_TASK_READER";
    UserRolesEnum["AviaryBuildingTaskReader"] = "AVIARY_BUILDING_TASK_READER";
    UserRolesEnum["ResearchTaskReader"] = "RESEARCH_TASK_READER";
    UserRolesEnum["TaskWriter"] = "TASK_WRITER";
    UserRolesEnum["IncubationTaskWriter"] = "INCUBATION_TASK_WRITER";
    UserRolesEnum["AviaryBuildingTaskWriter"] = "AVIARY_BUILDING_TASK_WRITER";
    UserRolesEnum["ResearchTaskWriter"] = "RESEARCH_TASK_WRITER";
    UserRolesEnum["SecurityReader"] = "SECURITY_READER";
    UserRolesEnum["SecurityWriter"] = "SECURITY_WRITER";
    UserRolesEnum["Admin"] = "ADMIN";
})(UserRolesEnum = exports.UserRolesEnum || (exports.UserRolesEnum = {}));
function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
exports.UserFromJSON = UserFromJSON;
function UserFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !runtime_1.exists(json, 'id') ? undefined : json['id'],
        'username': !runtime_1.exists(json, 'username') ? undefined : json['username'],
        'password': !runtime_1.exists(json, 'password') ? undefined : json['password'],
        'firstName': !runtime_1.exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !runtime_1.exists(json, 'lastName') ? undefined : json['lastName'],
        'department': !runtime_1.exists(json, 'department') ? undefined : json['department'],
        'tasks': !runtime_1.exists(json, 'tasks') ? undefined : (new Set(json['tasks'].map(Task_1.TaskFromJSON))),
        'groups': !runtime_1.exists(json, 'groups') ? undefined : (new Set(json['groups'].map(Group_1.GroupFromJSON))),
        'roles': !runtime_1.exists(json, 'roles') ? undefined : json['roles'],
    };
}
exports.UserFromJSONTyped = UserFromJSONTyped;
function UserToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'username': value.username,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'department': value.department,
        'tasks': value.tasks === undefined ? undefined : (Array.from(value.tasks).map(Task_1.TaskToJSON)),
        'groups': value.groups === undefined ? undefined : (Array.from(value.groups).map(Group_1.GroupToJSON)),
        'roles': value.roles,
    };
}
exports.UserToJSON = UserToJSON;
