/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserIdInputTO
 */
export interface UserIdInputTO {
    /**
     *
     * @type {number}
     * @memberof UserIdInputTO
     */
    id: number;
}
export declare function UserIdInputTOFromJSON(json: any): UserIdInputTO;
export declare function UserIdInputTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdInputTO;
export declare function UserIdInputTOToJSON(value?: UserIdInputTO | null): any;
