/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViolationTO } from './ViolationTO';
/**
 *
 * @export
 * @interface ValidationResponseTO
 */
export interface ValidationResponseTO {
    /**
     *
     * @type {Array<ViolationTO>}
     * @memberof ValidationResponseTO
     */
    violations?: Array<ViolationTO>;
}
export declare function ValidationResponseTOFromJSON(json: any): ValidationResponseTO;
export declare function ValidationResponseTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationResponseTO;
export declare function ValidationResponseTOToJSON(value?: ValidationResponseTO | null): any;
