"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var runtime_1 = require("../runtime");
function ViolationTOFromJSON(json) {
    return ViolationTOFromJSONTyped(json, false);
}
exports.ViolationTOFromJSON = ViolationTOFromJSON;
function ViolationTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'fieldName': !runtime_1.exists(json, 'fieldName') ? undefined : json['fieldName'],
        'message': !runtime_1.exists(json, 'message') ? undefined : json['message'],
    };
}
exports.ViolationTOFromJSONTyped = ViolationTOFromJSONTyped;
function ViolationTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'fieldName': value.fieldName,
        'message': value.message,
    };
}
exports.ViolationTOToJSON = ViolationTOToJSON;
