/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WikiDTO
 */
export interface WikiDTO {
    /**
     *
     * @type {number}
     * @memberof WikiDTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof WikiDTO
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof WikiDTO
     */
    text?: string;
    /**
     *
     * @type {string}
     * @memberof WikiDTO
     */
    image?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof WikiDTO
     */
    relatedPages?: Array<string>;
}
export declare function WikiDTOFromJSON(json: any): WikiDTO;
export declare function WikiDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WikiDTO;
export declare function WikiDTOToJSON(value?: WikiDTO | null): any;
