/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateAviaryRequest {
    simpleEntityInputTO: SimpleEntityInputTO;
}
export interface DeleteAviaryRequest {
    id: number;
}
export interface UpdateAviaryRequest {
    id: number;
    simpleEntityInputTO: SimpleEntityInputTO;
}
/**
 *
 */
export declare class AviaryTypeApi extends runtime.BaseAPI {
    /**
     */
    createAviaryRaw(requestParameters: CreateAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    createAviary(requestParameters: CreateAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    deleteAviaryRaw(requestParameters: DeleteAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    deleteAviary(requestParameters: DeleteAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    getAllAviariesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     */
    getAllAviaries(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     */
    updateAviaryRaw(requestParameters: UpdateAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    updateAviary(requestParameters: UpdateAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
