/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateAviaryRequest {
    body?: SimpleEntityInputTO;
}
export interface DeleteAviaryRequest {
    id: number;
}
export interface UpdateAviaryRequest {
    id: number;
    body?: SimpleEntityInputTO;
}
/**
 *
 */
export declare class AviaryTypeApi extends runtime.BaseAPI {
    /**
     * createAviary
     */
    createAviaryRaw(requestParameters: CreateAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * createAviary
     */
    createAviary(requestParameters: CreateAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * deleteAviary
     */
    deleteAviaryRaw(requestParameters: DeleteAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * deleteAviary
     */
    deleteAviary(requestParameters: DeleteAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * getAllAviaries
     */
    getAllAviariesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     * getAllAviaries
     */
    getAllAviaries(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     * updateAviary
     */
    updateAviaryRaw(requestParameters: UpdateAviaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * updateAviary
     */
    updateAviary(requestParameters: UpdateAviaryRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
