/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateDecorationRequest {
    body?: SimpleEntityInputTO;
}
export interface DeleteDecorationRequest {
    id: number;
}
export interface UpdateDecorationRequest {
    id: number;
    body?: SimpleEntityInputTO;
}
/**
 *
 */
export declare class DecorationTypeApi extends runtime.BaseAPI {
    /**
     * createDecoration
     */
    createDecorationRaw(requestParameters: CreateDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * createDecoration
     */
    createDecoration(requestParameters: CreateDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * deleteDecoration
     */
    deleteDecorationRaw(requestParameters: DeleteDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * deleteDecoration
     */
    deleteDecoration(requestParameters: DeleteDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * getAllDecorations
     */
    getAllDecorationsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     * getAllDecorations
     */
    getAllDecorations(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     * updateDecoration
     */
    updateDecorationRaw(requestParameters: UpdateDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * updateDecoration
     */
    updateDecoration(requestParameters: UpdateDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
