/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateDecorationRequest {
    simpleEntityInputTO: SimpleEntityInputTO;
}
export interface DeleteDecorationRequest {
    id: number;
}
export interface UpdateDecorationRequest {
    id: number;
    simpleEntityInputTO: SimpleEntityInputTO;
}
/**
 *
 */
export declare class DecorationTypeApi extends runtime.BaseAPI {
    /**
     */
    createDecorationRaw(requestParameters: CreateDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    createDecoration(requestParameters: CreateDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    deleteDecorationRaw(requestParameters: DeleteDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    deleteDecoration(requestParameters: DeleteDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    getAllDecorationsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     */
    getAllDecorations(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     */
    updateDecorationRaw(requestParameters: UpdateDecorationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    updateDecoration(requestParameters: UpdateDecorationRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
