/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateDinosaurRequest {
    simpleEntityInputTO: SimpleEntityInputTO;
}
export interface DeleteDinosaurRequest {
    id: number;
}
export interface UpdateDinosaurRequest {
    id: number;
    simpleEntityInputTO: SimpleEntityInputTO;
}
/**
 *
 */
export declare class DinosaurTypeApi extends runtime.BaseAPI {
    /**
     */
    createDinosaurRaw(requestParameters: CreateDinosaurRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    createDinosaur(requestParameters: CreateDinosaurRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    deleteDinosaurRaw(requestParameters: DeleteDinosaurRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    deleteDinosaur(requestParameters: DeleteDinosaurRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    getAllDinosaursRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     */
    getAllDinosaurs(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     */
    updateDinosaurRaw(requestParameters: UpdateDinosaurRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    updateDinosaur(requestParameters: UpdateDinosaurRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
