/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateDinosaurTypeRequest {
    simpleEntityInputTO: SimpleEntityInputTO;
}
export interface DeleteDinosaurTypeRequest {
    id: number;
}
export interface UpdateDinosaurTypeRequest {
    id: number;
    simpleEntityInputTO: SimpleEntityInputTO;
}
/**
 *
 */
export declare class DinosaurApi extends runtime.BaseAPI {
    /**
     */
    createDinosaurTypeRaw(requestParameters: CreateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    createDinosaurType(requestParameters: CreateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    deleteDinosaurTypeRaw(requestParameters: DeleteDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    deleteDinosaurType(requestParameters: DeleteDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    getAllDinosaurStatusesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;
    /**
     */
    getAllDinosaurStatuses(initOverrides?: RequestInit): Promise<Array<string>>;
    /**
     */
    getAllDinosaurTypesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     */
    getAllDinosaurTypes(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     */
    updateDinosaurTypeRaw(requestParameters: UpdateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    updateDinosaurType(requestParameters: UpdateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
