/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { RevisionEntryTO, SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateDinosaurTypeRequest {
    body?: SimpleEntityInputTO;
}
export interface DeleteDinosaurTypeRequest {
    id: number;
}
export interface UpdateDinosaurTypeRequest {
    id: number;
    body?: SimpleEntityInputTO;
}
/**
 *
 */
export declare class DinosaurApi extends runtime.BaseAPI {
    /**
     * createDinosaurType
     */
    createDinosaurTypeRaw(requestParameters: CreateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * createDinosaurType
     */
    createDinosaurType(requestParameters: CreateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * deleteDinosaurType
     */
    deleteDinosaurTypeRaw(requestParameters: DeleteDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * deleteDinosaurType
     */
    deleteDinosaurType(requestParameters: DeleteDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     * getAllDinosaurStatuses
     */
    getAllDinosaurStatusesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;
    /**
     * getAllDinosaurStatuses
     */
    getAllDinosaurStatuses(initOverrides?: RequestInit): Promise<Array<string>>;
    /**
     * getAllDinosaurTypes
     */
    getAllDinosaurTypesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     * getAllDinosaurTypes
     */
    getAllDinosaurTypes(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     * upcoming revisions
     */
    getUpcomingRevisionsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<RevisionEntryTO>>>;
    /**
     * upcoming revisions
     */
    getUpcomingRevisions(initOverrides?: RequestInit): Promise<Array<RevisionEntryTO>>;
    /**
     * updateDinosaurType
     */
    updateDinosaurTypeRaw(requestParameters: UpdateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     * updateDinosaurType
     */
    updateDinosaurType(requestParameters: UpdateDinosaurTypeRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
