"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var runtime = require("../runtime");
var models_1 = require("../models");
/**
 *
 */
var DocumentApi = /** @class */ (function (_super) {
    __extends(DocumentApi, _super);
    function DocumentApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     */
    DocumentApi.prototype.createDocumentRaw = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var queryParameters, headerParameters, response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (requestParameters.documentType === null || requestParameters.documentType === undefined) {
                            throw new runtime.RequiredError('documentType', 'Required parameter requestParameters.documentType was null or undefined when calling createDocument.');
                        }
                        if (requestParameters.httpEntity === null || requestParameters.httpEntity === undefined) {
                            throw new runtime.RequiredError('httpEntity', 'Required parameter requestParameters.httpEntity was null or undefined when calling createDocument.');
                        }
                        queryParameters = {};
                        if (requestParameters.httpEntity !== undefined) {
                            queryParameters['httpEntity'] = requestParameters.httpEntity;
                        }
                        headerParameters = {};
                        return [4 /*yield*/, this.request({
                                path: "/api/document/{documentType}".replace("{" + "documentType" + "}", encodeURIComponent(String(requestParameters.documentType))),
                                method: 'POST',
                                headers: headerParameters,
                                query: queryParameters,
                            }, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, new runtime.JSONApiResponse(response, function (jsonValue) { return models_1.DocumentOutputTOFromJSON(jsonValue); })];
                }
            });
        });
    };
    /**
     */
    DocumentApi.prototype.createDocument = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.createDocumentRaw(requestParameters, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [4 /*yield*/, response.value()];
                    case 2: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    /**
     */
    DocumentApi.prototype.getDocumentsByTypeRaw = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var queryParameters, headerParameters, response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (requestParameters.documentType === null || requestParameters.documentType === undefined) {
                            throw new runtime.RequiredError('documentType', 'Required parameter requestParameters.documentType was null or undefined when calling getDocumentsByType.');
                        }
                        queryParameters = {};
                        headerParameters = {};
                        return [4 /*yield*/, this.request({
                                path: "/api/document/{documentType}".replace("{" + "documentType" + "}", encodeURIComponent(String(requestParameters.documentType))),
                                method: 'GET',
                                headers: headerParameters,
                                query: queryParameters,
                            }, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, new runtime.JSONApiResponse(response, function (jsonValue) { return jsonValue.map(models_1.DocumentOutputTOFromJSON); })];
                }
            });
        });
    };
    /**
     */
    DocumentApi.prototype.getDocumentsByType = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.getDocumentsByTypeRaw(requestParameters, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [4 /*yield*/, response.value()];
                    case 2: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    /**
     */
    DocumentApi.prototype.updateDocumentRaw = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var queryParameters, headerParameters, response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (requestParameters.documentType === null || requestParameters.documentType === undefined) {
                            throw new runtime.RequiredError('documentType', 'Required parameter requestParameters.documentType was null or undefined when calling updateDocument.');
                        }
                        if (requestParameters.documentId === null || requestParameters.documentId === undefined) {
                            throw new runtime.RequiredError('documentId', 'Required parameter requestParameters.documentId was null or undefined when calling updateDocument.');
                        }
                        if (requestParameters.httpEntity === null || requestParameters.httpEntity === undefined) {
                            throw new runtime.RequiredError('httpEntity', 'Required parameter requestParameters.httpEntity was null or undefined when calling updateDocument.');
                        }
                        queryParameters = {};
                        if (requestParameters.httpEntity !== undefined) {
                            queryParameters['httpEntity'] = requestParameters.httpEntity;
                        }
                        headerParameters = {};
                        return [4 /*yield*/, this.request({
                                path: "/api/document/{documentType}/{documentId}".replace("{" + "documentType" + "}", encodeURIComponent(String(requestParameters.documentType))).replace("{" + "documentId" + "}", encodeURIComponent(String(requestParameters.documentId))),
                                method: 'PUT',
                                headers: headerParameters,
                                query: queryParameters,
                            }, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, new runtime.JSONApiResponse(response, function (jsonValue) { return models_1.DocumentOutputTOFromJSON(jsonValue); })];
                }
            });
        });
    };
    /**
     */
    DocumentApi.prototype.updateDocument = function (requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.updateDocumentRaw(requestParameters, initOverrides)];
                    case 1:
                        response = _a.sent();
                        return [4 /*yield*/, response.value()];
                    case 2: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    return DocumentApi;
}(runtime.BaseAPI));
exports.DocumentApi = DocumentApi;
/**
    * @export
    * @enum {string}
    */
var CreateDocumentDocumentTypeEnum;
(function (CreateDocumentDocumentTypeEnum) {
    CreateDocumentDocumentTypeEnum["ThemeZoneProject"] = "THEME_ZONE_PROJECT";
    CreateDocumentDocumentTypeEnum["DinosaurPassport"] = "DINOSAUR_PASSPORT";
    CreateDocumentDocumentTypeEnum["TechnologicalMap"] = "TECHNOLOGICAL_MAP";
    CreateDocumentDocumentTypeEnum["AviaryPassport"] = "AVIARY_PASSPORT";
    CreateDocumentDocumentTypeEnum["ResearchData"] = "RESEARCH_DATA";
})(CreateDocumentDocumentTypeEnum = exports.CreateDocumentDocumentTypeEnum || (exports.CreateDocumentDocumentTypeEnum = {}));
/**
    * @export
    * @enum {string}
    */
var GetDocumentsByTypeDocumentTypeEnum;
(function (GetDocumentsByTypeDocumentTypeEnum) {
    GetDocumentsByTypeDocumentTypeEnum["ThemeZoneProject"] = "THEME_ZONE_PROJECT";
    GetDocumentsByTypeDocumentTypeEnum["DinosaurPassport"] = "DINOSAUR_PASSPORT";
    GetDocumentsByTypeDocumentTypeEnum["TechnologicalMap"] = "TECHNOLOGICAL_MAP";
    GetDocumentsByTypeDocumentTypeEnum["AviaryPassport"] = "AVIARY_PASSPORT";
    GetDocumentsByTypeDocumentTypeEnum["ResearchData"] = "RESEARCH_DATA";
})(GetDocumentsByTypeDocumentTypeEnum = exports.GetDocumentsByTypeDocumentTypeEnum || (exports.GetDocumentsByTypeDocumentTypeEnum = {}));
/**
    * @export
    * @enum {string}
    */
var UpdateDocumentDocumentTypeEnum;
(function (UpdateDocumentDocumentTypeEnum) {
    UpdateDocumentDocumentTypeEnum["ThemeZoneProject"] = "THEME_ZONE_PROJECT";
    UpdateDocumentDocumentTypeEnum["DinosaurPassport"] = "DINOSAUR_PASSPORT";
    UpdateDocumentDocumentTypeEnum["TechnologicalMap"] = "TECHNOLOGICAL_MAP";
    UpdateDocumentDocumentTypeEnum["AviaryPassport"] = "AVIARY_PASSPORT";
    UpdateDocumentDocumentTypeEnum["ResearchData"] = "RESEARCH_DATA";
})(UpdateDocumentDocumentTypeEnum = exports.UpdateDocumentDocumentTypeEnum || (exports.UpdateDocumentDocumentTypeEnum = {}));
