/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { DocumentOutputTO } from '../models';
export interface CreateDocumentRequest {
    documentType: CreateDocumentDocumentTypeEnum;
    body: string;
}
export interface GetDocumentsByTypeRequest {
    documentType: GetDocumentsByTypeDocumentTypeEnum;
}
export interface UpdateDocumentRequest {
    documentType: UpdateDocumentDocumentTypeEnum;
    documentId: number;
    httpEntity: string;
}
/**
 *
 */
export declare class DocumentApi extends runtime.BaseAPI {
    /**
     */
    createDocumentRaw(requestParameters: CreateDocumentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DocumentOutputTO>>;
    /**
     */
    createDocument(requestParameters: CreateDocumentRequest, initOverrides?: RequestInit): Promise<DocumentOutputTO>;
    /**
     */
    getDocumentsByTypeRaw(requestParameters: GetDocumentsByTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<DocumentOutputTO>>>;
    /**
     */
    getDocumentsByType(requestParameters: GetDocumentsByTypeRequest, initOverrides?: RequestInit): Promise<Array<DocumentOutputTO>>;
    /**
     */
    updateDocumentRaw(requestParameters: UpdateDocumentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DocumentOutputTO>>;
    /**
     */
    updateDocument(requestParameters: UpdateDocumentRequest, initOverrides?: RequestInit): Promise<DocumentOutputTO>;
}
/**
    * @export
    * @enum {string}
    */
export declare enum CreateDocumentDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
/**
    * @export
    * @enum {string}
    */
export declare enum GetDocumentsByTypeDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
/**
    * @export
    * @enum {string}
    */
export declare enum UpdateDocumentDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
