/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { DocumentOutputTO } from '../models';
export interface CreateDocumentRequest {
    documentType: CreateDocumentDocumentTypeEnum;
}
export interface CreateResearchDataRequest {
    researchData: string;
    attachment: Blob;
}
export interface GetDocumentsByTypeRequest {
    documentType: GetDocumentsByTypeDocumentTypeEnum;
}
export interface UpdateDocumentRequest {
    documentType: UpdateDocumentDocumentTypeEnum;
    documentId: number;
    body?: {
        [key: string]: object;
    };
}
/**
 *
 */
export declare class DocumentApi extends runtime.BaseAPI {
    /**
     * createDocument
     */
    createDocumentRaw(requestParameters: CreateDocumentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DocumentOutputTO>>;
    /**
     * createDocument
     */
    createDocument(requestParameters: CreateDocumentRequest, initOverrides?: RequestInit): Promise<DocumentOutputTO>;
    /**
     * createResearchData
     */
    createResearchDataRaw(requestParameters: CreateResearchDataRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DocumentOutputTO>>;
    /**
     * createResearchData
     */
    createResearchData(requestParameters: CreateResearchDataRequest, initOverrides?: RequestInit): Promise<DocumentOutputTO>;
    /**
     * get all document types
     */
    getDocumentTypesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;
    /**
     * get all document types
     */
    getDocumentTypes(initOverrides?: RequestInit): Promise<string>;
    /**
     * getDocumentsByType
     */
    getDocumentsByTypeRaw(requestParameters: GetDocumentsByTypeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<DocumentOutputTO>>>;
    /**
     * getDocumentsByType
     */
    getDocumentsByType(requestParameters: GetDocumentsByTypeRequest, initOverrides?: RequestInit): Promise<Array<DocumentOutputTO>>;
    /**
     * updateDocument
     */
    updateDocumentRaw(requestParameters: UpdateDocumentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DocumentOutputTO>>;
    /**
     * updateDocument
     */
    updateDocument(requestParameters: UpdateDocumentRequest, initOverrides?: RequestInit): Promise<DocumentOutputTO>;
}
/**
    * @export
    * @enum {string}
    */
export declare enum CreateDocumentDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
/**
    * @export
    * @enum {string}
    */
export declare enum GetDocumentsByTypeDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
/**
    * @export
    * @enum {string}
    */
export declare enum UpdateDocumentDocumentTypeEnum {
    ThemeZoneProject = "THEME_ZONE_PROJECT",
    DinosaurPassport = "DINOSAUR_PASSPORT",
    TechnologicalMap = "TECHNOLOGICAL_MAP",
    AviaryPassport = "AVIARY_PASSPORT",
    ResearchData = "RESEARCH_DATA"
}
