/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { GroupInputTO, GroupOutputTO, UserIdInputTO, UserOutputTO } from '../models';
export interface AddUserRequest {
    groupId: number;
    userIdInputTO: UserIdInputTO;
}
export interface CreateGroupRequest {
    groupInputTO: GroupInputTO;
}
export interface RemoveUserRequest {
    groupId: number;
    userId: number;
}
export interface UpdateGroupRequest {
    groupId: number;
    groupInputTO: GroupInputTO;
}
/**
 *
 */
export declare class GroupApi extends runtime.BaseAPI {
    /**
     */
    addUserRaw(requestParameters: AddUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;
    /**
     */
    addUser(requestParameters: AddUserRequest, initOverrides?: RequestInit): Promise<string>;
    /**
     */
    createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GroupOutputTO>>;
    /**
     */
    createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit): Promise<GroupOutputTO>;
    /**
     */
    getGroupRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<GroupOutputTO>>>;
    /**
     */
    getGroup(initOverrides?: RequestInit): Promise<Array<GroupOutputTO>>;
    /**
     */
    getRolesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;
    /**
     */
    getRoles(initOverrides?: RequestInit): Promise<Array<string>>;
    /**
     */
    getUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UserOutputTO>>>;
    /**
     */
    getUsers(initOverrides?: RequestInit): Promise<Array<UserOutputTO>>;
    /**
     */
    removeUserRaw(requestParameters: RemoveUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;
    /**
     */
    removeUser(requestParameters: RemoveUserRequest, initOverrides?: RequestInit): Promise<string>;
    /**
     */
    updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GroupOutputTO>>;
    /**
     */
    updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit): Promise<GroupOutputTO>;
}
