/**
 * JurassicCRM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fitisovdmtr@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { GroupOutputTO, MultipartFile, UserIdInputTO, UserOutputTO } from '../models';
export interface AddUserRequest {
    groupId: number;
    body?: UserIdInputTO;
}
export interface CreateGroupRequest {
    avatar: Blob;
    groupInfo: string;
}
export interface RemoveUserRequest {
    groupId: number;
    userId: number;
}
export interface UpdateGroupRequest {
    groupId: number;
    name?: string;
    roles?: Set<UpdateGroupRolesEnum>;
    userIds?: Set<number>;
    avatar?: MultipartFile;
    description?: string;
}
/**
 *
 */
export declare class GroupApi extends runtime.BaseAPI {
    /**
     * addUser
     */
    addUserRaw(requestParameters: AddUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;
    /**
     * addUser
     */
    addUser(requestParameters: AddUserRequest, initOverrides?: RequestInit): Promise<string>;
    /**
     * createGroup
     */
    createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GroupOutputTO>>;
    /**
     * createGroup
     */
    createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit): Promise<GroupOutputTO>;
    /**
     * getGroup
     */
    getAllGroupsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<GroupOutputTO>>>;
    /**
     * getGroup
     */
    getAllGroups(initOverrides?: RequestInit): Promise<Array<GroupOutputTO>>;
    /**
     * getRoles
     */
    getRolesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;
    /**
     * getRoles
     */
    getRoles(initOverrides?: RequestInit): Promise<Array<string>>;
    /**
     * getUsers
     */
    getUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UserOutputTO>>>;
    /**
     * getUsers
     */
    getUsers(initOverrides?: RequestInit): Promise<Array<UserOutputTO>>;
    /**
     * removeUser
     */
    removeUserRaw(requestParameters: RemoveUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;
    /**
     * removeUser
     */
    removeUser(requestParameters: RemoveUserRequest, initOverrides?: RequestInit): Promise<string>;
    /**
     * updateGroup
     */
    updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GroupOutputTO>>;
    /**
     * updateGroup
     */
    updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit): Promise<GroupOutputTO>;
}
/**
    * @export
    * @enum {string}
    */
export declare enum UpdateGroupRolesEnum {
    DocumentReader = "DOCUMENT_READER",
    DinosaurPassportReader = "DINOSAUR_PASSPORT_READER",
    AviaryPassportReader = "AVIARY_PASSPORT_READER",
    ThemeZoneProjectReader = "THEME_ZONE_PROJECT_READER",
    TechnologicalMapReader = "TECHNOLOGICAL_MAP_READER",
    ResearchDataReader = "RESEARCH_DATA_READER",
    DocumentWriter = "DOCUMENT_WRITER",
    DinosaurPassportWriter = "DINOSAUR_PASSPORT_WRITER",
    AviaryPassportWriter = "AVIARY_PASSPORT_WRITER",
    ThemeZoneProjectWriter = "THEME_ZONE_PROJECT_WRITER",
    TechnologicalMapWriter = "TECHNOLOGICAL_MAP_WRITER",
    ResearchDataWriter = "RESEARCH_DATA_WRITER",
    TaskReader = "TASK_READER",
    IncubationTaskReader = "INCUBATION_TASK_READER",
    AviaryBuildingTaskReader = "AVIARY_BUILDING_TASK_READER",
    ResearchTaskReader = "RESEARCH_TASK_READER",
    TaskWriter = "TASK_WRITER",
    IncubationTaskWriter = "INCUBATION_TASK_WRITER",
    AviaryBuildingTaskWriter = "AVIARY_BUILDING_TASK_WRITER",
    ResearchTaskWriter = "RESEARCH_TASK_WRITER",
    SecurityReader = "SECURITY_READER",
    SecurityWriter = "SECURITY_WRITER",
    Admin = "ADMIN"
}
