/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { LogEntry } from '../models';
/**
 *
 */
export declare class LogsApi extends runtime.BaseAPI {
    /**
     */
    getLogsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<LogEntry>>>;
    /**
     */
    getLogs(initOverrides?: RequestInit): Promise<Array<LogEntry>>;
}
