/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SimpleEntityInputTO, SimpleEntityOutputTO } from '../models';
export interface CreateResearchRequest {
    simpleEntityInputTO: SimpleEntityInputTO;
}
export interface DeleteResearchRequest {
    id: number;
}
export interface UpdateResearchRequest {
    id: number;
    simpleEntityInputTO: SimpleEntityInputTO;
}
/**
 *
 */
export declare class ResearchApi extends runtime.BaseAPI {
    /**
     */
    createResearchRaw(requestParameters: CreateResearchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    createResearch(requestParameters: CreateResearchRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    deleteResearchRaw(requestParameters: DeleteResearchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    deleteResearch(requestParameters: DeleteResearchRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
    /**
     */
    getAllResearchesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SimpleEntityOutputTO>>>;
    /**
     */
    getAllResearches(initOverrides?: RequestInit): Promise<Array<SimpleEntityOutputTO>>;
    /**
     */
    updateResearchRaw(requestParameters: UpdateResearchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SimpleEntityOutputTO>>;
    /**
     */
    updateResearch(requestParameters: UpdateResearchRequest, initOverrides?: RequestInit): Promise<SimpleEntityOutputTO>;
}
