/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
/**
 *
 */
export declare class RoleApi extends runtime.BaseAPI {
    /**
     */
    getAllRolesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;
    /**
     */
    getAllRoles(initOverrides?: RequestInit): Promise<void>;
}
