/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { FullUserInputTO, FullUserOutputTO } from '../models';
export interface CreateUserRequest {
    fullUserInputTO: FullUserInputTO;
}
export interface GetUserByIdRequest {
    userId: number;
}
export interface UpdateUserRequest {
    userId: number;
    fullUserInputTO: FullUserInputTO;
}
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI {
    /**
     */
    createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
    /**
     */
    getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
    /**
     */
    getUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullUserOutputTO>>>;
    /**
     */
    getUsers(initOverrides?: RequestInit): Promise<Array<FullUserOutputTO>>;
    /**
     */
    updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
}
