/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { FullUserInputTO, FullUserOutputTO } from '../models';
export interface CreateUserRequest {
    fullUserInputTO: FullUserInputTO;
}
export interface FindAllByRolesRequest {
    roles?: Set<FindAllByRolesRolesEnum>;
}
export interface GetUserByIdRequest {
    userId: number;
}
export interface UpdateUserRequest {
    userId: number;
    fullUserInputTO: FullUserInputTO;
}
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI {
    /**
     */
    createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
    /**
     */
    findAllByRolesRaw(requestParameters: FindAllByRolesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullUserOutputTO>>>;
    /**
     */
    findAllByRoles(requestParameters: FindAllByRolesRequest, initOverrides?: RequestInit): Promise<Array<FullUserOutputTO>>;
    /**
     */
    getCurrentUserRolesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Set<string>>>;
    /**
     */
    getCurrentUserRoles(initOverrides?: RequestInit): Promise<Set<string>>;
    /**
     */
    getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
    /**
     */
    getUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullUserOutputTO>>>;
    /**
     */
    getUsers(initOverrides?: RequestInit): Promise<Array<FullUserOutputTO>>;
    /**
     */
    updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<FullUserOutputTO>>;
    /**
     */
    updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<FullUserOutputTO>;
}
/**
    * @export
    * @enum {string}
    */
export declare enum FindAllByRolesRolesEnum {
    DocumentReader = "DOCUMENT_READER",
    DinosaurPassportReader = "DINOSAUR_PASSPORT_READER",
    AviaryPassportReader = "AVIARY_PASSPORT_READER",
    ThemeZoneProjectReader = "THEME_ZONE_PROJECT_READER",
    TechnologicalMapReader = "TECHNOLOGICAL_MAP_READER",
    ResearchDataReader = "RESEARCH_DATA_READER",
    DocumentWriter = "DOCUMENT_WRITER",
    DinosaurPassportWriter = "DINOSAUR_PASSPORT_WRITER",
    AviaryPassportWriter = "AVIARY_PASSPORT_WRITER",
    ThemeZoneProjectWriter = "THEME_ZONE_PROJECT_WRITER",
    TechnologicalMapWriter = "TECHNOLOGICAL_MAP_WRITER",
    ResearchDataWriter = "RESEARCH_DATA_WRITER",
    TaskReader = "TASK_READER",
    IncubationTaskReader = "INCUBATION_TASK_READER",
    AviaryBuildingTaskReader = "AVIARY_BUILDING_TASK_READER",
    ResearchTaskReader = "RESEARCH_TASK_READER",
    TaskWriter = "TASK_WRITER",
    IncubationTaskWriter = "INCUBATION_TASK_WRITER",
    AviaryBuildingTaskWriter = "AVIARY_BUILDING_TASK_WRITER",
    ResearchTaskWriter = "RESEARCH_TASK_WRITER",
    SecurityReader = "SECURITY_READER",
    SecurityWriter = "SECURITY_WRITER",
    Admin = "ADMIN"
}
