/**
 * Jurassic CRM API
 * Jurassic CRM
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { WikiDTO } from '../models';
export interface CreateWikiPageRequest {
    title: string;
    text: string;
    image: Array<string>;
    relatedPages: Array<string>;
}
export interface DeleteWikiByTitleRequest {
    title: string;
}
export interface GetWikiByTitleRequest {
    title: string;
}
export interface UpdateWikiPageRequest {
    id: number;
    title: string;
    text: string;
    image: Array<string>;
    relatedPages: Array<string>;
}
/**
 *
 */
export declare class WikiControllerApi extends runtime.BaseAPI {
    /**
     */
    createWikiPageRaw(requestParameters: CreateWikiPageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>>;
    /**
     */
    createWikiPage(requestParameters: CreateWikiPageRequest, initOverrides?: RequestInit): Promise<number>;
    /**
     */
    deleteWikiByTitleRaw(requestParameters: DeleteWikiByTitleRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>>;
    /**
     */
    deleteWikiByTitle(requestParameters: DeleteWikiByTitleRequest, initOverrides?: RequestInit): Promise<number>;
    /**
     */
    getAllTitlesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;
    /**
     */
    getAllTitles(initOverrides?: RequestInit): Promise<Array<string>>;
    /**
     */
    getWikiByTitleRaw(requestParameters: GetWikiByTitleRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WikiDTO>>;
    /**
     */
    getWikiByTitle(requestParameters: GetWikiByTitleRequest, initOverrides?: RequestInit): Promise<WikiDTO>;
    /**
     */
    updateWikiPageRaw(requestParameters: UpdateWikiPageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>>;
    /**
     */
    updateWikiPage(requestParameters: UpdateWikiPageRequest, initOverrides?: RequestInit): Promise<number>;
}
