export const AVIARY_TYPE_ID = "aviaryTypeId"
export const AVIARY_SQUARE = "aviarySquare"
export const AVIARY_BUILT_DATE = "builtDate"
export const AVIARY_REVISION_PERIOD = "revisionPeriod"
export const AVIARY_STATUS = "status"
export const AVIARY_CODE = "code"
export const AVIARY_DESCRIPTION = "description"