import {
    DOCUMENT_NAME,
    RESEARCH_ATTACHMENT,
    RESEARCH_ATTACHMENT_NAME,
    RESEARCH_ID, RESEARCH_IS_NEW, RESEARCH_MATERIAL_DESCRIPTION,
    RESEARCH_NAME,
    RESEARCH_NAME_ID
} from "./fieldNames";

export default TO => ({
    [RESEARCH_NAME_ID]: {
        [RESEARCH_NAME]: TO.research.name,
        [RESEARCH_ID]: TO.research.id
    },
    [RESEARCH_ATTACHMENT_NAME]: TO[RESEARCH_ATTACHMENT_NAME],
    [RESEARCH_ATTACHMENT]: TO[RESEARCH_ATTACHMENT],
    [RESEARCH_MATERIAL_DESCRIPTION]: TO[RESEARCH_MATERIAL_DESCRIPTION],
    [RESEARCH_IS_NEW]: false,
    [DOCUMENT_NAME]: TO[DOCUMENT_NAME]
})