import {DINOSAUR_EGG_CREATION_STEPS, DINOSAUR_INCUBATION_STEPS, DINOSAUR_TYPE_ID, DOCUMENT_NAME} from "./fieldNames";

export default {
    [DOCUMENT_NAME]: '',
    [DINOSAUR_INCUBATION_STEPS]: [''],
    [DINOSAUR_EGG_CREATION_STEPS]: [''],
    [DINOSAUR_TYPE_ID]: ''
}