export const TASK_NAME = "name"
export const TASK_ASSIGNEE_ID = "assigneeId"
export const TASK_PRIORITY_ID = "taskPriorityId"
export const TASK_DESCRIPTION = "description"
export const TASK_TYPE = "taskType"
export const AVIARY_TYPE_ID = "aviaryTypeId"
export const AVIARY_SQUARE = "square"