version: '3.1'
services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: jurassicdb
    ports:
    - 5432:5432
  testbase:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: jurassicdbtest
    ports:
      - 15432:5432
