server:
  max-http-header-size: 10000000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
  thymeleaf:
    

  datasource:
    url: jdbc:postgresql://localhost:5432/jurassicdb
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
logging:
  level:
    org:
      hibernate:
        type: trace
jurassic:
  rolesToPrivileges:
    ROLE_ADMIN:
      - ALL
    ROLE_DOCUMENT_READER:
      - READ
    ROLE_DOCUMENT_WRITER:
      - WRITE
    ROLE_DOCUMENT_ADMIN:
      - DELETE
    ROLE_EMPLOYEE:
      - ACCESS_HR
    ROLE_TASK_READER:
      - READ_TASK
      - WRITE_TASK
    ROLE_GROUP_EDITOR:
      - WRITE_GROUP
    TASK_AUTHOR:
      - TASK_AUTHOR_STUB
debug: true
