server:
  max-http-header-size: 10000000

spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
  thymeleaf:
    excluded-view-names:
    - wiki.html

  datasource:
    url: jdbc:postgresql://localhost:5432/jurassicdb
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
logging:
  level:
    org:
      hibernate:
        type: trace
debug: true

crm:
  aviary:
    revision:
      num: 2