export const RESEARCH_NAME_ID = "researchNameId"
export const RESEARCH_ATTACHMENT = "attachment"
export const RESEARCH_MATERIAL_DESCRIPTION = "description"
export const RESEARCH_ID = "researchId"
export const RESEARCH_NAME = "researchName"
export const RESEARCH_IS_NEW = "isNew"